### ISSUE TITLE
Fade or gray out "Selection color" on opposite panel

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#113]
Just a small "aesthetics/usability" consideration. IMO could be helpful to make more evident the current selection, fading color selection on the opposite panel. 
Sometimes at a very very first look I can't immediately tell what file is focused, and have to look the top-panel background to figure it out.

I see two scenarios for this
 - automatically decrease saturation of the "Selection color"
 - add another color in preference (maybe just at right of the selection color, so we don't mess too much the preferences dialog)

**Comment by MeanEYE** [comment]
This has been already done on GTK3 branch to which we will soon switch. Thanks for reporting this.
! [This is how it currently looks like](https://cloud.githubusercontent.com/assets/1911594/7670300/be7a4f2c-fc9f-11e4-83fc-2a06242546b6.png). Please ignore main menu and some other visual issues as this branch is still not polished enough to be released as main.

**Comment by bfx** [comment]
The GTK3 branch looks just right. Thanks as always for your effort!
