### ISSUE TITLE
Operation error when copying from sftp path

### ISSUE THREAD

**Issue by johnjohndoe** [MeanEYE/Sunflower#123]
I am trying to copy a folder from a sftp path to a local path. The process stops and the following error message pops up:

> Operation error
> There was a problem with reading specified directory. What would you like to do?
> No such file or directory

Here is a screenshot:

![Sunflower error dialog](https://cloud.githubusercontent.com/assets/144518/8149807/d68c1882-12d1-11e5-86a7-87c6623cfb56.png)

I am using v.0.2 (59) on Ubuntu 14.04.

**Comment by MeanEYE** [comment]
Hm. Interesting. I think this was fixed already, but I'll accept the issue and close once I confirm this indeed is fixed.

**Comment by johnjohndoe** [comment]
:+1:
