### ISSUE TITLE
Adding a Bookmark to the Toolbar

### ISSUE THREAD

**Issue by omarsadat** [MeanEYE/Sunflower#124]
Hello,

Just to let you know  I am on Ubuntu X64 V. 15.04 Vivid.

I click on  Edit/Preferences/Toolbar/add

At  that  small window I can not type anything it will not allow you.........UNLESS I CLOSE THE MAIN WINDOW ' PREFERENCES ' THEN I CAN START TYPING.

And yet the particular bookmark will  not show up at the toolbar till I do the go to the path mentioned above and then click on the Bookmark that I just created and click Edit then save then save again only at that point would the Bookmark would show up.

That is one bug the 2nd one is the rearranging the bookmarks using the up and down arrows DO NOT WORK PERIOD.

I like the program, and I would like to see it PERFECT.

Thank you for all your hard work.

Om

June 18 2015

**Comment by MeanEYE** [comment]
Thanks for reporting this. Can you include screen shot of this happening. I am not quite sure about which window you are talking about. Thanks!

**Comment by joshas** [comment]
@MeanEYE , this issue probably can be closed, as we no longer have classic menu and #400 solved issues with modal parents.

**Comment by MeanEYE** [comment]
Probably yes. If this persists, please reopen.
