### ISSUE TITLE
copying images from one folder to  another

### ISSUE THREAD

**Issue by omarsadat** [MeanEYE/Sunflower#125]
Hello,

just to  inform you that when i select some image from one folder and click on the copy button on the Toolbar on the bottom it freezes and I can not cancel or exit the only way is to kill it.

So Hopefully you will find a fix in the future versions for all of us, and thank you.

Om
June 18 2015

**Comment by MeanEYE** [comment]
Hi. Thanks for reporting this. Can you start Sunflower from terminal and include output when this happens here?

**Comment by omarsadat** [comment]
Thank you,

Please teach me how to start Sunflower from the terminal.

I tried to type:

sunflower                      It did not work

I  tried
sunflower &                   it did not work

I tried
<sunflowr> &                  it did not work.

Alos there is a problem in communicating through the email I worte the
peoblem on your website and I write I think 2 of them. You responded
through the email and it would be a good idea to include the original topic
in the reply.

I do like Sunflower very much, and if you can fix the issues then there is
a great potential to grow and one day be like Directory Opus for windows.

I would love to assist you just let me know,

Thank you for your hard work.

Om
June 20 2015

**Comment by MeanEYE** [comment]
Thanks for kind words. How did you install Sunflower. There should be a `sunflower` command either way.

**Comment by omarsadat** [comment]
Hello,

I tried to send you 2 files compressed in .rar but your server did not
accept them. They are a video I made to show you the problems as I go
theough them live.

If you have  another email I send them to you so you can watch and see for
yourself.

Thank you,

Om

June 20 2015

**Comment by MeanEYE** [comment]
I just checked my spam folder and your email is not there either. Please note that GMail has file limit of 20 or so MB, so it's possible that's the reason email got rejected. You can use mega.nz to send those files if you wish.

On 06/20/2015 10:38 PM, omarsadat wrote:
> Hello,
> 
> I tried to send you 2 files compressed in .rar but your server did not
> accept them. They are a video I made to show you the problems as I go
> theough them live.
> 
> If you have another email I send them to you so you can watch and see for
> yourself.
> 
> Thank you,
> 
> Om
> 
> June 20 2015
> 
> On Sat, Jun 20, 2015 at 9:51 AM, Mladen Mijatov <notifications@github.com>
> wrote:
> 
>> Thanks for kind words. How did you install Sunflower. There should be a
>> sunflower command either way.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MeanEYE/Sunflower/issues/125#issuecomment-113789534>.
>>
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/MeanEYE/Sunflower/issues/125#issuecomment-113818413>.
> 

-- 
Mladen Mijatov
Key ID: 4096R/83EFD5A0 2013-08-18
Tox ID: B82DADBC7614F887F2ACB7A4F29E848D937452113C9EBBA39DCB3E260096945A934361722B51

**Comment by omarsadat** [comment]
Hello again Miaden,

I was surprised how can this  email __  http://mega.nz/  __ address would
work I do have Maga too. But I wanted to try and was not possible it is not
an email ad
dress " @ ".

So no problem now you got me to learn something brand new. I do have an
account with Mega too.
So I did some test between 2 browsers and it is a success.By the way Gmail
is now 25 MB.

Please go here and you will  see the 3 files download them. You have to
include your key with the link because as you will see you can only see
what I want to you see* and vise versa.*


https://mega.co.nz/#F!AtUDlT6B!2qTrlyYYJkoYgwQIjlbhbQ


Thank you again Miaden,


IN ADDITION TO THE PARTITIONING  PROGRAM I WROTE TO YOU ABOUT - WOULD YOU
 PLEASE LET ME OF A *MACRO PROGRAM *THAT WORKS ON UBUNTU 15.04 I  TRIED SO
 MANY AND DO NOT WORK AT ALL . I MISS MY  MACRO EXPRESS FOR WINDOWS AND DO
NOT LIKE  THE  IDEA OF USING WINE ON  UBUNTU I MIGHT AS WELL JUST STAY WITH
WINDOWS.

Om

June 20

**Comment by MeanEYE** [comment]
Hey @omarsadat sorry for delayed response. I want to tie this issue off. Since version 0.3 was released today, can you please check and see if this issue is still present? Thanks

**Comment by omarsadat** [comment]
I will at a later day, but to let you know I found out the problem not from
your side it is from Ubuntu itself.

Many thanks,
Om

**Comment by MeanEYE** [comment]
Oh, okay. Thanks. Let me know how test goes so we can perhaps get around it.
