### ISSUE TITLE
CTRL+<Arrow> on a directory open that directory on the <Arrow> panel

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#127]
I know I'm totally TotalCommander biased, but for me seems really natural, this scenario.
- Focus on a directory (panel left)
- CTRL+Right
- The focused directory is opened on the right panel
  (Opposite way too of course)

**Comment by MeanEYE** [comment]
You mean open highlighted directory?

**Comment by bfx** [comment]
Yes, highlighted!
