### ISSUE TITLE
Support .hidden

### ISSUE THREAD

**Issue by dufferzafar** [MeanEYE/Sunflower#132]
A `.hidden` file in a directory contains a list of filenames to hide. This works with [Nautilus, Nemo](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory#GNOME) etc. 

And I guess [Dolphin](https://bugs.kde.org/show_bug.cgi?id=246260) has the support now too.

We could go a step further and support regex/globs in the `.hidden` file.

I think #53 is a bit similar to this?

**Comment by MeanEYE** [comment]
#53 is direct opposite from this. But if other file managers support this, we'll support as well to keep consistency.
