### ISSUE TITLE
sunflower does not start from fishshell

### ISSUE THREAD

**Issue by hwmrocker** [MeanEYE/Sunflower#135]
when i start it from bash, everything is ok

```
Traceback (most recent call last):
  File "/usr/share/sunflower/Sunflower.py", line 25, in <module>
    search_paths = os.environ["PATH"].split(os.pathsep)
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PATH'
```

**Comment by MeanEYE** [comment]
`PATH` environment variable lists search paths for binary executables. Is there a `fish` equivalent?

**Comment by hwmrocker** [comment]
i just saw that sunflower worked on a different machine from fish.

I checked both configs, and realized that I modified exported the PATH variable the wrong way.
I used `set -g PATH ... $PATH` instead of `set -gx PATH ... $PATH`

Nevertheless, thx for your fast fix

**Comment by MeanEYE** [comment]
Well, it was more of a mitigation instead of fix. But it made us realize that sometime in future this might be an issue. Although as @ArseniyK already mentioned in IRC chat, `PATH` is defined by ISO standard for POSIX compliant systems so it should be implemented by every shell.

**Comment by hwmrocker** [comment]
since i modified the PATH veriable, it was just set for the shell and not for the child processes. I am new to fish and still learning.

**Comment by MeanEYE** [comment]
Well, issue is resolved. That's all that matters. :)

**Comment by hwmrocker** [comment]
:) thx, this is a great file manager btw

**Comment by MeanEYE** [comment]
Thanks. We are preparing new version to be released soon. And along the way GTK3 version is almost ready for prime time. :) So lots of new stuff coming soon.
