### ISSUE TITLE
Launching Sublime Text 2 from Sunflower issue

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#137]
If I launch Sublime Text 2 from Sunflower, it starts with file "&" (ampersand) already open. It doesn't happen on other file managers.

**Comment by MeanEYE** [comment]
Can you provide a screen shot? Sorry for late reply.

**Comment by joshas** [comment]
Here's what I get when I launch Sublime Text 2 from Sunflower (not one tab with "&" name):
![xubuntu-sublime2-sunflower](https://cloud.githubusercontent.com/assets/79141/9388958/25ca807c-4771-11e5-9ed5-b75683cbadbc.png)

Launching from Thunar results in clean work environment, without files:
![xubuntu-sublime2-fm](https://cloud.githubusercontent.com/assets/79141/9388974/47641aea-4771-11e5-92e0-3c4d52fafbc7.png)

**Comment by MeanEYE** [comment]
Can you explain how you start Sublime? Do you open a certain file with it?

**Comment by joshas** [comment]
I press Enter on sublime_text executable. Sublime Text 2 is just extracted from zip to a folder, not installed to system.

**Comment by MeanEYE** [comment]
Okay. Now I know where to look for. Thanks!

**Comment by MeanEYE** [comment]
I've pushed some fixes. Can you check current branch and see if this is still happening?

**Comment by joshas** [comment]
Yes, the latest commits fixes this issue.

**Comment by MeanEYE** [comment]
Good. I thought as much that was the problem. Sorry for the delay in fixing.
