### ISSUE TITLE
Hide vertical scrollbar when all items fits on one page

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#139]
Currently vertical scrollbar is always displayed. It would be nice if it would be displayed only when needed.

**Comment by MeanEYE** [comment]
It's always visible because ti changes width of the elements when showing/hiding scroll bar. It's easy to implement this feature, but I am not entirely sure it's a good thing to do. I'll leave this open for now. GTK3 has much better scroll bar implementation so we'll see how it behaves then.

**Comment by joshas** [comment]
With GTK3 overlay scrollbars not changing content width, could vertical scroll be set to `Gtk.PolicyType.AUTOMATIC` ? This way interface will look a bit cleaner for directories with few items and hovering mouse over scrollbar won't display useless scrollbar that interferes with file list interactions.
Or should it be made as preference, with default to display vertical scrollbar?

**Comment by MeanEYE** [comment]
They should be made automatic at this point since they, as you pointed out, don't affect the width of content.
