### ISSUE TITLE
Add copy Queue

### ISSUE THREAD

**Issue by carnager** [MeanEYE/Sunflower#142]
Copying a file while another file transfer is ongoing will simply start another one. This can cause quite some I/O, depending on hardware, esp. when more than 2 transfers are going on.

I propose a way of queueing copy/move operations, like totalcommander does. (There you can click a Queue Button in the Copy dialog)

**Comment by MeanEYE** [comment]
Thanks for reporting this. Queues are already planned, but they have been delayed until we switch to GTK3 which should happen immediately after releasing next version.
