### ISSUE TITLE
Navigation with left/right arrows

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#147]
Currently navigating in file panes with left/right arrows opens directory contents inline. It would be nice to have an option, to switch left/right key functionality to go inside directory (right key) and go back up (right key) without opening files listing inline.

**Comment by MeanEYE** [comment]
All bindings can be changed, including behavior of `left` and `right` arrows. Did you try remapping and see how this behaves.

**Comment by joshas** [comment]
Thanks, I remapped them now. Works like a charm.

**Comment by MeanEYE** [comment]
Glad to hear that!
