### ISSUE TITLE
Hide cursor from inactive pane

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#148]
It would be nice if cursor from inactive pane could be turned off (by default or as an option). While tab header is quite big and should have enough indication, which pane is active, I usually start looking at cursors and get confused when both of them are active.

**Comment by MikeWallaceDev** [comment]
Yep, I also have problems with the inactive pane looking like it is active.

**Comment by MeanEYE** [comment]
This is already fixed in GTK3 version. While it's not hidden it's considerably dimmer (50% transparent). Fixing it in GTK2 would require some nasty hacks.
