### ISSUE TITLE
A whitelist of "hidden files"

### ISSUE THREAD

**Issue by jlx84** [MeanEYE/Sunflower#151]
Is it possible to have a user-editable whitelist of files/directories which filename begins with a dot and still list them in a panel even when hidden files are not visible? For example .gitignore file could be whitelisted. I am not sure if this feature would affect negatively speed of directory listing but it would be nice (for me).

**Comment by MeanEYE** [comment]
That feature just landed a week ago. It will be part of 0.3 release which I plan on releasing soon. :) Thanks for requesting this feature.

![screenshot from 2015-11-23 20-40-14](https://cloud.githubusercontent.com/assets/1911594/11347578/6fa97b84-9222-11e5-8ca5-d60d7867af54.png)
