### ISSUE TITLE
Unable to load plugin "owner_column"

### ISSUE THREAD

**Issue by mseed** [MeanEYE/Sunflower#154]
Function Edit -> Preferences -> Plugins -> owner_column do not work.
When enabled, terminal output is:
```
Error: Unable to load plugin "owner_column": cannot import name Column
```

Tested with Sunflower 0.2 (59).

**Comment by MeanEYE** [comment]
Did you get line number with this error message?

**Comment by mseed** [comment]
No line numbers in this message.

**Comment by MeanEYE** [comment]
Okay, thanks. Will try to reproduce and along the way fix error reporting on that one.
