### ISSUE TITLE
Launcher script doesn't pass on command line arguments.

### ISSUE THREAD

**Issue by nemonein** [MeanEYE/Sunflower#157]
Thank you for your great effort.
Total commander has an option, to start with a specific directory.
If I use 'totalcmd /R=c:/windows' for example, it shows c:/windows directory on the right panel.

Does Sunflower has an option like this?
I tried 'sunflower --help (or -H)' to find the what options it has, but there was no response at all. It just launched Sunflower.

**Comment by MeanEYE** [comment]
Yes it does. In order to make `--help` work you need Python's `argparse` module. If the directory you want to load is always the same, there's also an option in _Preferences_ under _Item list_ and _Directories_ tab. There you can configure which directories to always load instead of saved ones.

Following is the output of `--help`. Do note that you can specify flags more than once in case you want to open more than on path.
```
usage: Sunflower.py [-h] [-v] [-p] [-t] [-l PATH] [-r PATH] [-L PATH]
                    [-R PATH]

Sunflower file manager

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         print version and exit
  -p, --no-plugins      skip loading additional plugins
  -t, --no-load-tabs    skip loading saved tabs
  -l PATH, --left-tab PATH
                        open new tab on the left notebook
  -r PATH, --right-tab PATH
                        open new tab on the right notebook
  -L PATH, --left-terminal PATH
                        open terminal tab on the left notebook
  -R PATH, --right-terminal PATH
                        open terminal tab on the right notebook
```

It seems there is a bug with launcher script which skips all the arguments. So I'll be marking this as a bug report and changing its title.

**Comment by MeanEYE** [comment]
Can you please double-check if command line parameters work with this module installed before I go on to bug hunt? Just to confirm bug really exists.

**Comment by nemonein** [comment]
Thanks for the reply.

* OS : Ubuntu 14.04 (64bit)
* Sunflower : 0.2.59 (by atareao-team's ppa)
* Module : python-argh, python-argcomplete (Ubuntu Packages) installed

/usr/share/sunflower/Sunflower.py -h works.

> $ /usr/share/sunflower/Sunflower.py -h
> usage: Sunflower.py [-h] [-v] [-p] [-t] [-l PATH] [-r PATH] [-L PATH]
>                    [-R PATH]
>
> Sunflower file manager
>
> optional arguments:
> -h, --help            show this help message and exit
>  -v, --version         print version and exit
>  -p, --no-plugins      skip loading additional plugins
>  -t, --no-load-tabs    skip loading saved tabs
>  -l PATH, --left-tab PATH
>                        open new tab on the left notebook
>  -r PATH, --right-tab PATH
>                        open new tab on the right notebook
>  -L PATH, --left-terminal PATH
>                        open terminal tab on the left notebook
>  -R PATH, --right-terminal PATH
>                        open terminal tab on the right notebook

However, just 'sunflower --help(or -h)' returns nothing about parameters.
> $ sunflower --help 
> /usr/share/sunflower/application/plugins/file_list/file_list.py:318: GtkWarning: #IA__gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
  int(gtk.Settings().get_property('gtk-font-name').split()[-1])

**Comment by ArseniyK** [comment]
/usr/bin/sunfllower should looks like https://github.com/MeanEYE/Sunflower/blob/develop/dist/sunflower

**Comment by MeanEYE** [comment]
@ArseniyK I think there might be a problem with quotes there. It's fine as long as there's only one parameter, but what happens with more? Say for example someone specifies `-l / -r /`. In this case those will be passed inside of `""`, which might be the source of the problem and parser can't pick them up.

**Comment by ArseniyK** [comment]
No problem with quotes, he use atareao-team's ppa and in their paсkage /usr/bin/sunflower dont pass any params
```
#!/bin/bash
cd /usr/share/sunflower
python Sunflower.py
```

**Comment by MeanEYE** [comment]
Why would they change our launcher script or is it simply outdated again? Either way @nemonein can you download a package from [here](http://sunflower-fm.org/download) for your distribution and reinstall it. See if that works.

**Comment by nemonein** [comment]
I tried the package you uploded, and it works fine.
Thanks, guys, and Happy New Year!!

**Comment by MeanEYE** [comment]
Thanks @nemonein and @ArseniyK. Am closing this as it's not issue on our part.
