### ISSUE TITLE
HiDpi support

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [MeanEYE/Sunflower#159]
More and more often users are find themselves in use of hidpi screens where scaling ratio of 2:1 or more is vital. Sunflower does fine most of the part with 2 visible exceptions:
1) window size by default is too small, and should be adjusted according to scale ratio
2) column width should be scaled aswell, i.e. left colum if setting window is way too narrow.

**Comment by MeanEYE** [comment]
Thanks for reporting this. Version 0.4 is based on GTK3 and will fully support scaling. Additional feature should be made to make window size more appropriate.

**Comment by joshas** [comment]
Did anyone recently test Sunflower from develop branch on HiDPI displays? I tried running it at 125% fractional scaling and looks like it was correctly upscaled. Haven't noticed any items that are too small. Initial window size was proportionally scaled up too.

**Comment by MeanEYE** [comment]
Since we are no longer writing custom widgets, or at least not painting them, this should be fixed now. Thank you for testing.
