### ISSUE TITLE
After GTK3 switch - still importing GTK2 libraries

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#172]
application/keyring.py is still using GTK2 gnomekeyring

Migrate to 
    from gi.repository import GnomeKeyring

**Comment by cmallwitz** [comment]
application/widgets/thumbnail_view.py - same issue - here we do: "import gnome.ui"

**Comment by cmallwitz** [comment]
and:

application/plugins/file_list/file_list.py:2095:				with gtk.gdk.lock:

**Comment by MeanEYE** [comment]
Thanks!

**Comment by cmallwitz** [comment]
Resolved
