### ISSUE TITLE
After GTK3 switch - code assume GTK version > 3.12.0

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#173]
application/main_window.py is calling Gtk.HeaderBar.set_has_subtitle() which is marked new as of 3.12.0

Ubuntu 14.04.3 LTS is on GTK 3.10.8

Should we sprinkle our code with line like the one below or come up with a better approach?

if ( Gtk.get_major_version(), Gtk.get_minor_version(), Gtk.get_micro_version() ) > (3, 12, 0):
			self.header_bar.set_has_subtitle(True)

This issue may occur in other places too...

**Comment by cmallwitz** [comment]
application/plugins/file_list/file_list.py:1288 should be

               self._store.set_sort_column_id(Gtk.TreeSortable.UNSORTED_SORT_COLUMN_ID, True)

But I get an error that Gtk.TreeSortable.UNSORTED_SORT_COLUMN_ID doesn't exist.

**Comment by cmallwitz** [comment]
Probably same

Traceback (most recent call last):
  File "/home/christian/tech/IdeaProjects/Sunflower_remote_develop/application/widgets/breadcrumbs.py", line 140, in __draw_event
    attribute = Pango.AttrForeground.new(
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Pango' object has no attribute 'AttrForeground'

**Comment by cmallwitz** [comment]
I submitted a pull request for the "self.header_bar.set_has_subtitle(True)" thing ...

**Comment by MeanEYE** [comment]
We should handle version checks before we run into them. File `application/main.py` does some of these checks.

**Comment by cmallwitz** [comment]
well - I think if it just small stuff like new (purely additional) methods
like in

if hasattr(self.header_bar, 'set_has_subtitle'):
   self.header_bar.set_has_subtitle(True)

then a call using hasattr() should be fine before we start building
something complicated.

Christian

**Comment by MeanEYE** [comment]
Am not entirely sure that's the best approach even though we did it in the past. GTK+ developers added and removed things all over the place in version 3. Picking some base version and running with it might be the best approach. But in this instance it's justified as it doesn't take away from experience.

**Comment by cmallwitz** [comment]
Resolved but for the breadcrumb/Pango issue which will have to addressed separately.
