### ISSUE TITLE
Hello !

### ISSUE THREAD

**Issue by Koljan1970** [MeanEYE/Sunflower#174]
Sorry but the program locale Ukrainian Sunflower in a Russian translation .... I want to help translate it into Ukrainian if you do not mind.

**Comment by MeanEYE** [comment]
So we use [Transifex](https://www.transifex.com/way2cu/sunflower/) to translate Sunflower. That means people translate strings there, and I just pull them into the program. If there are issues with translations, that should ideally be sorted out on that site and with people in charge of those translations.

Feel free to apply to be a translator for Sunflower and I'll happily add you to language of your preference. :) Thanks again for opening this issue.
