### ISSUE TITLE
After GTK3 switch - Sunflower doesn't start on Debian Jessie due to missing GConf

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#177]
(Latest develop code base pulled fresh from github)

On a vanilla Debian Jessie installation Sunflower doesn't start because it fails
main.py:9    gi.require_version('GConf', '2.0')

The exception raised is "Namespace GConf not available"

But it certainly looks like that gconf is available/installed in general (I have a ~/.gconf directory, gconftool and dconf are installed) - could it be that something is missing from python/gi?

On an Ubuntu machine I can find /usr/lib/girepository-1.0/GConf-2.0.typelib - but not on the Jessie box.

Note: Latest release branch works on the same box.

**Comment by MeanEYE** [comment]
I'll check. Am not sure we even need `gconf`. Apart from reading terminal fonts and similar things, there's very little need for this package.

**Comment by cmallwitz** [comment]
Resolved
