### ISSUE TITLE
alphabetical order prefers capital letters, and diminishes diacritics

### ISSUE THREAD

**Issue by nbbn** [MeanEYE/Sunflower#179]
Hello, when I sort filenames, capital letters are before the rest and diacritics after all, e.g.:

```
CoreOS
aaaa_should_be_First
coreos_other
vagrant
ćoreos
```

I don't see any configuration to change this behavior.
IMO, the right way is to give choice or sort A, a, ą, B, b, C, c, ć, etc.

**Comment by MeanEYE** [comment]
Can you please check if option in _Preferences -> Item list -> Operation_ named _Case sensitive item sorting_ solves your problem? Thanks.

**Comment by nbbn** [comment]
This option work as expected, except diacritics.
To cut a long story short, there is more than one problem with diacritics. I hope, screenshots describe it well.
![2016-02-02-021115_1366x768_scrot](https://cloud.githubusercontent.com/assets/7264317/12736676/a56cc62e-c952-11e5-824d-982b480dd9ba.png)
![2016-02-02-021046_1366x768_scrot](https://cloud.githubusercontent.com/assets/7264317/12736677/a56e2bae-c952-11e5-8bf9-133849184c74.png)

**Comment by joshas** [comment]
Looks like sorting with diacritics works correctly on more recent GTK3 versions. Tried on Xubuntu 18.04.5 LiveCD - sorting was not working correctly, but on Xubuntu 20.04.1 and Fedora 32 (with latest updates) all files starting with non-English characters are sorted correctly.

**Comment by MeanEYE** [comment]
Hm, did you try with the new change I did to sorting algorithm?

**Comment by joshas** [comment]
Tested with the latest version from develop branch.

**Comment by MeanEYE** [comment]
Okay. So this issue is no longer valid?

**Comment by joshas** [comment]
I presume that it was fixed by recent versions of GTK lib.

**Comment by MeanEYE** [comment]
Okay. Will close. Thank you for testing.
