### ISSUE TITLE
RPMs of version 0.3.61 are 0 byte-sized. 

### ISSUE THREAD

**Issue by baldimir** [MeanEYE/Sunflower#180]
Hi,

when trying to download RPM build, the file is 0 bytes in size. The download link, which I am trying is here [1]. I'm using latest Chrome (48.0.2564.97 (64-bit)).

[1] http://sunflower-fm.org/pub/sunflower-0.3.61-1.noarch.rpm

**Comment by MeanEYE** [comment]
Sorry, I don't know sync failed. It's fixed now.

**Comment by baldimir** [comment]
Thanks, it works now :)
