### ISSUE TITLE
Sunflower doesn't start VLC correct

### ISSUE THREAD

**Issue by MatthiasKlees** [MeanEYE/Sunflower#183]
Hi,

the new SunflowerFM (sunflower-0.3.61-1.all.deb) has some problems with '#' in filenames and VLC. Files like "Artist xyz - Track #1.mp3" won't start in VLC.

**Comment by MeanEYE** [comment]
Version 0.3.61 is not GTK3, but this bug is valid. Thanks for reporting. It will be fixed.

**Comment by joshas** [comment]
@MeanEYE This issue can be closed, as it is fixed in develop branch.
