### ISSUE TITLE
Usage the semver standard for versioning

### ISSUE THREAD

**Issue by nervgh** [MeanEYE/Sunflower#188]
Hello, @MeanEYE 

Great job! 
I use the Sunflower 0.2 (59) during in last 6 mounts. It works pretty good :+1: 

What do you think about using the [semver](http://semver.org/) for versioning?
Looks like the [Nautilus](https://github.com/GNOME/nautilus) and many another projects already use it.

**Comment by nervgh** [comment]
Hmm... I downloaded latest version `sunflower-0.3.61-1`. it seems like the Sunflower 0.3.x already use it. Sorry, for the trouble. Git tags confused me :confused:

**Comment by MeanEYE** [comment]
Heh. Thanks for reporting this _issue_. Yeah, I decided to switch to a bit more reasonable version pattern. In all honesty I think I should have already marked some release as 1.0, but to me nothing feels like a complete version to me.

**Comment by nervgh** [comment]
I mean what
1. your git tags `x.x-x` and the Sunflower preview `x.x (x)` do not match with the semver pattern `x.x.x`
2. after changing minor version (MAJOR.MINOR.PATCH), developer sets to zero the patch version usually (for example, `0.2-59` should was be `0.3-0` instead `0.3-60`)

> Patch version MUST be reset to 0 when minor version is incremented
http://semver.org/

If you approve the server standard for further development I think next verion may be `x.x.x` :smiley:
You do not need change the major version If you do not "want".

One more thanks for the Sunflower :sunflower:
