### ISSUE TITLE
non-printable characters in filenames are interpreted

### ISSUE THREAD

**Issue by nbbn** [MeanEYE/Sunflower#198]
Hello,
I have (utf-8 encoding):
```
4859 0a47
```
in filename. It means HY< LINE FEED (LF) >G
Sunflower in list view will show file in two lines.
I think, that the better way is to show it like Nautilus or XFE, that use replacement characters.
Something like  or �.

EDIT: I see, that in rename window all characters are shown inline. I think, that it should be presented in the same way on a list of files.

**Comment by MeanEYE** [comment]
Okay, I didn't think about line feeds in file names. Can you include some screen shots of how other programs handle this so we can replicate the behavior.

Sorry for delayed response!

**Comment by nbbn** [comment]
File on list and in rename window (sunflower):
![2lines](https://cloud.githubusercontent.com/assets/7264317/13381885/45a662f2-de67-11e5-98d5-3e45426c627d.png)
Nautilus:
![nautilus](https://cloud.githubusercontent.com/assets/7264317/13381887/593e4b0e-de67-11e5-9705-1b1316798e15.png)
Xfe:
![xfe](https://cloud.githubusercontent.com/assets/7264317/13381891/61078454-de67-11e5-99b2-5d9c36fb14bb.png)

IMO rename/nautilus display is the best.
