### ISSUE TITLE
Sunflower window divided not equally on LinuxMint-17.2-xfce

### ISSUE THREAD

**Issue by insolor** [MeanEYE/Sunflower#201]
On LinuxMint 17.2 an 17.3 (xfce) Sunflower window is divided not equally:
![sunflowermint](https://cloud.githubusercontent.com/assets/2442833/13555564/b07939d4-e3d4-11e5-9d61-bb9ab01e5622.png)
I'm moving the divider to the center, but after restart it moves to the previous position.

This problem is related to Sunflower 0.3 (61), in the version 0.3 (60) the window was divided equally.

**Comment by MeanEYE** [comment]
Difference between `61` and `60` is really only fixing a delete bug, nothing else. This looks like it's defaulting to initial size we set to avoid some other issues. Can you please verify that value is properly saved in `~/.config/sunflower/windows.json`. Key name is `handle_position` for `main` window.

**Comment by insolor** [comment]
@MeanEYE 
On Linux Mint 17.2:
```
{
    "main": {
        "geometry": "1366x606+0+0",
        "handle_position": 480,
        "hide_on_close": false,
        "state": 1
    }
}
```

Contents of the file on lubuntu 15.10 (where the problem doesn't occur):
```
{
    "main": {
        "geometry": "960x550+202+29", 
        "handle_position": 480, 
        "hide_on_close": false, 
        "state": 1
    }
}
```

**Comment by MeanEYE** [comment]
Thanks for replying. Was terminal tab open in both instances. Am thinking it might have something to do with this.

**Comment by insolor** [comment]
> Was terminal tab open in both instances.
Not sure what you mean. Terminal was opened only in the right panel, but opening it in the left one doesn't change the situation.
python-vte is installed on both Linux Mint machines. I've just installed it on Lubuntu 15.10 and opened a terminal tab in the right panel of Sunflower, then restarted the file manager, but after it the window is still divided equally.

**Comment by MeanEYE** [comment]
Okay, this is strange issue indeed. I'll take a look.

**Comment by MeanEYE** [comment]
You should try and test development branch by the way. It's possible this issue is GTK+ specific and we've changed version for 0.4 to GTK3.

**Comment by insolor** [comment]
@MeanEYE I tried the most recent version from the development branch, but it fails to run because of some exception:

```
insolor@insolor-LinuxMint17 ~/Sunflower $ ./Sunflower.py
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
**
ERROR:../../gi/pygobject.c:1017:pygobject_new_full: assertion failed: (tp != NULL)
```

I thought that it is because of some requirement not satisfied, and checked all the requirements from the DEPENDS file, it looks like everything from the "Require" section is installed.

**Comment by MeanEYE** [comment]
Oh, that's strange. I'll see if I can reproduce this issue on some of the computers from my developers in the company, they also use Mint. Sorry for the inconvenience.

**Comment by nervgh** [comment]
> Sunflower window divided not equally
> I'm moving the divider to the center, but after restart it moves to the previous position.

I saw same behavior on my PC with Ubuntu 15.10 but I can not reproduce it.

**Comment by MeanEYE** [comment]
This whole issue came to be when I added ability to change position of split. Before that application always forced 50:50. It is quite possible and right seems like the most likely issue that GTK+ as it creates widgets updates the size and somewhere in the middle of that we catch "realize" even which sometimes gives us broken values due to concurrency issue of sort.

I will however keep this issue open as I want to see if it can be reproduced with GTK3 version.

**Comment by insolor** [comment]
Can't reproduce anymore (Sunflower develop branch, LinuxMint 19.2). I think this issue can be closed now.

**Comment by MeanEYE** [comment]
Thanks for testing.
