### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by sevka** [MeanEYE/Sunflower#214]
Version from github (develop branch) crashes on start. I have Ubuntu 14.04.4.

sevka@sevka-laptop:~/Sunflower$ ./Sunflower.py
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
**
ERROR:../../gi/pygobject.c:1017:pygobject_new_full: assertion failed: (tp != NULL)
Failed running with python2.7

**Comment by joshas** [comment]
@MeanEYE Should this issue be closed, as develop version migrated to Python3?

**Comment by MeanEYE** [comment]
Yes it should. It's related to GTK2 used through GObject Introspection.
