### ISSUE TITLE
Externally touching a file doesn't change date in file list

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#228]
Seems to be present in released and current (GTK3 - develop) version.

file_list.py: _update_item_attributes_by_name(relative_path, parent) handling MonitorSignals.ATTRIBUTE_CHANGED only updates file mode.

**Comment by MeanEYE** [comment]
We need to make sure this is not by design. Touch changes modification time. If Sunflower is showing creation or access, that would explain it. Are you familiar what the behavior was like on previous version?

**Comment by cmallwitz** [comment]
We are definitely showing last modification time in the file list - you can see that when you leave and come back to directory with "touched" file it updates the timestamp.

Just "touching" triggers MonitorSignals.ATTRIBUTE_CHANGED and goes to update_item_attributes_by_name() - on MonitorSignals.CHANGED we pick up last modify timestamp in _update_item_details_by_name()

From file_list.py:

elif event is MonitorSignals.CHANGED:
   self._update_item_details_by_name(relative_path, parent)

elif event is MonitorSignals.ATTRIBUTE_CHANGED:
   self._update_item_attributes_by_name(relative_path, parent)

My test cases are:
1) touch a file -> triggers MonitorSignals.ATTRIBUTE_CHANGED but this isn't updating last modify timestamp, "refreshing" directory picks up the change though
2) chmod on file-> handled correctly through MonitorSignals.ATTRIBUTE_CHANGED
3) run a 'cat > file' on command line, leave it open and occasionally input another line with dummy text and press enter -> handled correctly through MonitorSignals.CHANGED

I verified that behaviour is the same in last pre-GTK3 build.

**Comment by cmallwitz** [comment]
How about this getting merged? I would like to cleanup my local repo ans start contributing more fixes after a long pause :-)
