### ISSUE TITLE
GTK3 - fast media preview not working

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#229]
First I had to: `apt-get install gir1.2-gnomedesktop-3.0` to get around
`from gi.repository import GnomeDesktop`
failing with
`ImportError: cannot import name GnomeDesktop`

But there is still a trace back in console:

> Traceback (most recent call last):
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugins/file_list/file_list.py", line 347, in _control_got_focus
    self._handle_cursor_change()
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugins/file_list/file_list.py", line 385, in _handle_cursor_change
    position = self._get_popup_menu_position()
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugins/file_list/file_list.py", line 1234, in _get_popup_menu_position
    window_x, window_y = self._parent.window.get_position()
AttributeError: 'MainWindow' object has no attribute 'window'

**Comment by cmallwitz** [comment]
Additionally, there are a few calls to Gtk.Widget.translate_coordinates(widget, x, y) that silently fails if widget isn't a widget

**Comment by MeanEYE** [comment]
Does this fix the issue with media preview? And as I can see others are affected as well. With same behavior?

**Comment by cmallwitz** [comment]
Yes - media prefix is working after the fix.

It wasn't an issue with media handling as such but with working out how to
position the preview. I replaced "window" with "get_window()" in a few
other places too (mostly around where to position pop up menus).

All these lines threw the same traceback re: "window" not being defined and
after the fix work as expected.

**Comment by MeanEYE** [comment]
Okay thanks!

**Comment by cmallwitz** [comment]
Resolved
