### ISSUE TITLE
GTK3 - command line arguments not working

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#232]
The way main.py sets up the application has GTK3 see any command line arguments before Sunfflower and, not knowing about them, exits before Sunflower MainWindow can process them.

**Comment by MeanEYE** [comment]
I don't see the issue. Why would `main.py` exit if there are no parameters?

**Comment by cmallwitz** [comment]
the problem is having some arguments - main.py doesn't stop itself but with
our current setup Gtk.Application will not come up when it finds any
unhandled command line options - just run "python ./Sunflower.py -r /etc"

**Comment by MeanEYE** [comment]
Okay, let me test first. Thanks for reporting.

**Comment by cmallwitz** [comment]
Fixed.
