### ISSUE TITLE
Translation not used everywhere

### ISSUE THREAD

**Issue by LionelR** [MeanEYE/Sunflower#236]
On Transiflex the French file is checked as 100% completed, but in the app not all strings are translated, specially in the menu bar.

**Comment by MeanEYE** [comment]
Can you provide which version you use. It's possible that translation was completed after version was released.

**Comment by LionelR** [comment]
Sunflower 0.3 (61)

**Comment by joshas** [comment]
@MeanEYE With recent main menu removal and translations updates this issue probably can be closed?

**Comment by MeanEYE** [comment]
For some reason French is still not being loaded, even strings that are translated.

**Comment by MeanEYE** [comment]
Hm, actually installed version has issues with French. Development is good. So this is most likely something to do with installation. I'll keep this open and double-check.

**Comment by MeanEYE** [comment]
Okay, I made several mistakes with translations. They should be fixed now. Please reopen if they are still not fixed.
