### ISSUE TITLE
Drag item = horizontally scrolling

### ISSUE THREAD

**Issue by LionelR** [MeanEYE/Sunflower#239]
If we drag an item from the left panel to the right panel, the left panel scrolls horizontally, and after we have to re-enable the "show horizontal scrollbar" to come back to an acceptable display

**Comment by joshas** [comment]
In most recent development version item dragging doesn't work at all, also "Show horizontal scrollbar" option was removed - issue is no longer reproducible.
@MeanEYE could this issue be closed?

**Comment by MeanEYE** [comment]
Issue can indeed be closed since there's no need for horizontal scrollbar anymore. However drag and drop is not working due to a different reason. Namely the same one (I think) that causes issues with copy and pasting items.
