### ISSUE TITLE
Version 0.3 .deb does not work Xubuntu 16.04

### ISSUE THREAD

**Issue by bysereg** [MeanEYE/Sunflower#243]
Version 0.3 .deb does not work Xubuntu 16.04, installed but does not start. A repository ppa:atareao/sunflower works.

**Comment by MeanEYE** [comment]
If you start `sunflower` from terminal. Do you get any errors?

**Comment by icyrockcom** [comment]
@MeanEYE I don't know if @bysereg had the same issue, but on Xubuntu 17.10 I'm getting this:

```
$ sunflower 
Traceback (most recent call last):
  File "/usr/share/sunflower/application/main.py", line 31, in <module>
    from gui.main_window import MainWindow
  File "/usr/share/sunflower/application/gui/main_window.py", line 31, in <module>
    from plugin_base.item_list import ItemList
  File "/usr/share/sunflower/application/plugin_base/item_list.py", line 11, in <module>
    from tools.viewer import Viewer
  File "/usr/share/sunflower/application/tools/viewer.py", line 2, in <module>
    import chardet
ImportError: No module named chardet
Failed running with python2.7
```

Installing the package:

```
$ sudo apt install python-chardet
```

solves the issue.

**Comment by MeanEYE** [comment]
@icyrockcom Yes, dependency wasn't set right in that version of package. It's quite possible it's the same issue.

**Comment by icyrockcom** [comment]
Thanks @MeanEYE - just to clarify, I installed the latest version from here: http://sunflower-fm.org/pub/sunflower-0.3.61-1.all.deb, so looks like it's still missing.

**Comment by MeanEYE** [comment]
You are right. It is indeed missing even in current code. Do you mind opening a new issue @icyrockcom? I'd like this fixed for next release.

**Comment by icyrockcom** [comment]
@MeanEYE I think there's already one: https://github.com/MeanEYE/Sunflower/issues/244

**Comment by MeanEYE** [comment]
Indeed that's the issue. Thanks!
