### ISSUE TITLE
Sunflower doesn't work on opensuse leap

### ISSUE THREAD

**Issue by ArjonBu** [MeanEYE/Sunflower#251]
I have installed it on opensuse leap and it doesn't launch. I don't usually report bugs so i have no idea what logs i should submit.

**Comment by MeanEYE** [comment]
Open the terminal and run `sunflower`. Let me know if there are any errors reported.

**Comment by Arjoni** [comment]
I get:
/usr/bin/sunflower: line 3: /usr/share/sunflower/Sunflower.py: Permission denied
/usr/bin/sunflower: line 3: exec: /usr/share/sunflower/Sunflower.py: cannot execute: Permission denied

PS: Use OBS (opensuse build service) to deliver updates easily and create free repos for all distros.

**Comment by MeanEYE** [comment]
Okay, so it's easy solution. You don't have execute permission on those files. Just add `+x` to them and you should be fine. As for OBS, yes am looking into it already.

**Comment by MeanEYE** [comment]
This issue has been fixed for 0.4 and for build script in 0.3-gtk2 branch. If it's not please let me know.
