### ISSUE TITLE
Sunflower.py needs to be set to executable on fedora.

### ISSUE THREAD

**Issue by welarson** [MeanEYE/Sunflower#252]
I installed the sunflower-0.3.61-1.noarch.rpm on Fedora 24 and when I tried to start the application it failed to start. Didn't take much digging to figure out that /usr/share/sunflower/Sunflower.py needed to be set executable. Worked great after that.

**Comment by welarson** [comment]
Peeked in the code and realized you've already addressed this.

**Comment by MeanEYE** [comment]
Yeah. Sorry for not releasing the hotfix. My RPM build is kind of out of commission right now. I'll make ti work as soon as possible. Thanks for reporting the issue though.
