### ISSUE TITLE
Language on linux mint 17.3 

### ISSUE THREAD

**Issue by lepimux** [MeanEYE/Sunflower#265]
After install the language is spanish , i guess :) and i can't change it 
I tried to uninstall , purge and re-install , same result 

Any way to get english or french ?

**Comment by MeanEYE** [comment]
Sunflower uses GetText for localization. Which means it looks for your local configuration for language and then load that one. You can always force different language to load by specifying `LANG` environment variable like so:

```
LANG=en sunflower
```

**Comment by lepimux** [comment]
My default language is french , and i dont know any word of spanish :) 
but i will force it with your solution. 
Thanks

**Comment by MeanEYE** [comment]
Can you please do `echo $LANG` and provide it here just to make sure there's no confusion in loading translation.

**Comment by lepimux** [comment]
xxxx@lepim-Dell ~ $ echo $LANG
fr_FR.UTF-8

**Comment by MeanEYE** [comment]
Well, it's configured as French. I don't know why it's loading as Spanish. This is so strange. Can you confirm solution I provided works?

**Comment by lepimux** [comment]
i maybe use an old repo check and tell me : 

xxxx@lepim-Dell ~ $ aptitude show sunflower
Paquet : sunflower                            
Nouveau: oui
État: installé
Automatiquement installé: non
Version : 0.2.59.pac.1-1ubuntu1
Priorité : optionnel
Section : misc
Responsable : Lorenzo Carbonell Cerezo <lorenzo.carbonell.cerezo@gmail.com>
Architecture : all
Taille décompressée : 2 342 k
Dépend: python, python-gtk2, python-imaging
Recommande: python-notify
Suggère: python-gnome2, python-argparse, python-mutagen, python-vte
Description : Small and highly customizable twin-panel file manager for Linux with support for plugins.

your solution work in a terminal , i just have to find a way to include it in the shortcut on cinnamon.

**Comment by MeanEYE** [comment]
You use PPA to install. PPA is not officially supported and this bug was present before. [Download the latest version](http://sunflower-fm.org/download) from our site and issue should be fixed.

**Comment by MeanEYE** [comment]
Oh, by the way, all you need to do is `sudo dpkg -i sunflower.deb` and it will upgrade existing one.

**Comment by ArseniyK** [comment]
yep in that ppa sunflower builds with es locale instead fr https://launchpadlibrarian.net/201450148/buildlog_ubuntu-trusty-i386.sunflower_0.2.59.pac.1-1ubuntu1_BUILDING.txt.gz

....
# Compile languages
msgfmt template1/bg.po -o /build/buildd/sunflower-0.2.59.pac.1/debian/sunflower/usr/share/locale-langpack/bg/LC_MESSAGES/sunflower.mo
msgfmt template1/cs.po -o /build/buildd/sunflower-0.2.59.pac.1/debian/sunflower/usr/share/locale-langpack/cs/LC_MESSAGES/sunflower.mo	
msgfmt template1/de.po -o /build/buildd/sunflower-0.2.59.pac.1/debian/sunflower/usr/share/locale-langpack/de/LC_MESSAGES/sunflower.mo	
msgfmt template1/es.po -o /build/buildd/sunflower-0.2.59.pac.1/debian/sunflower/usr/share/locale-langpack/es/LC_MESSAGES/sunflower.mo
msgfmt template1/es.po -o /build/buildd/sunflower-0.2.59.pac.1/debian/sunflower/usr/share/locale-langpack/fr/LC_MESSAGES/sunflower.mo
......

**Comment by lepimux** [comment]
ok thanks , sorry for my misstake , it is resolved with the newest version.

**Comment by MeanEYE** [comment]
It's not your mistake. :) Thanks for reporting it.
