### ISSUE TITLE
How to change language of the UI?

### ISSUE THREAD

**Issue by xak2000** [MeanEYE/Sunflower#267]
Hi!

I want to try a `Sunflower` but can't set it's UI language to English.

My Ubuntu language is RU. And I don't want to set global system language to English. But I prefer english language for some technical applications, like IDEs, File managers, git etc.

So I have `.bash_aliases` file in my home directory:
```
alias mc='env LANGUAGE=en mc'
alias sudo='env LANGUAGE=en sudo'
alias git='env LANGUAGE=en git'
```
It works fine for these applications.

But unfortunately it doesn't work with `Sunflower`.
When I add `alias sunflower='env LANGUAGE=en sunflower'`, it works, but only when I start sunflower from the terminal. When I start it using Unity `.desktop` file (through Dash), it still opens in russian.

I found this issue #265 and there you suggesting to use `LANG=en`, but this doesn't work even in terminal:
```
$ LANG=en sunflower

(process:30081): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

```

**Comment by ArseniyK** [comment]
Можешь изменить Exec в .desktop на Exec=/bin/sh -c "LANGUAGE=en sunflower"

**Comment by xak2000** [comment]
I found a way to do it!

I changed the `sunflower.desktop` file's line:
```
Exec=sunflower %U
```

To:
```
Exec=env LANGUAGE=en sunflower %U
```

And now it works.

Still unsure why it doesn't work from alias.

The full instructions to make it work:
> Copy `/usr/share/applications/sunflower.desktop` to some folder, then open the copy in your editor and change the line `Exec=sunflower %U` to `Exec=env LANGUAGE=en sunflower %U`.
After this, run `sudo desktop-file-install ./sunflower.desktop` to install updated file into Unity launcher (just editing the file inplace doesn't work, at least until reboot).
>
> Now you can run `Sunflower` from Unity's Dash and it's UI is in English!

I leave the issue as FAQ for the future googlers. :-)

**Comment by ArseniyK** [comment]
Aliases is part of shell, but .desktop dont use shell for running applications so desktop dont know anything about you shell alias.

**Comment by xak2000** [comment]
Thanks! That makes sense.

**Comment by MeanEYE** [comment]
Cool. You guys sorted it out. Thanks @ArseniyK.
