### ISSUE TITLE
All my custom commands vanished??

### ISSUE THREAD

**Issue by usamakh** [MeanEYE/Sunflower#268]
Today when i logged in my BunsenLabs x32 ..i opened Sunflower & to my amazement all my custom commands vanished ..there is nothing there??

THe bookmarks, locations & every other setting remains. Please tell me the location where it saves commands

**Comment by MeanEYE** [comment]
All the configuration is most likely in `~/.config/sunflower/`. If you don't have '~/.config` directory then it's just `~/.sunflower`. Custom commands are saved in file `commands.json`.

**Comment by MeanEYE** [comment]
Closing due to lack of information. Please reopen if this issue persists.
