### ISSUE TITLE
Does not run on Fedora

### ISSUE THREAD

**Issue by skontar** [MeanEYE/Sunflower#269]
Hi. I have tried to install `sunflower-0.3.61-1.noarch.rpm` on Fedora 25, but could not run it afterwards.

```
$ sunflower 
/usr/bin/sunflower: line 3: /usr/share/sunflower/Sunflower.py: Permission denied
/usr/bin/sunflower: line 3: exec: /usr/share/sunflower/Sunflower.py: cannot execute: Permission denied
```

Looks like a packaging problem, as https://github.com/MeanEYE/Sunflower/issues/251 seems to be the same problem but on SUSE.

**Comment by MeanEYE** [comment]
Thank you for reporting this. It seems to be predominant issue. I'll try to package new version today.

**Comment by Jipok** [comment]
@skontar, try
`chmod +x /usr/share/sunflower/Sunflower.py`

**Comment by MeanEYE** [comment]
This indeed is the solution. RPM installation/package script needs to set permission properly as well.

**Comment by BrokeRU** [comment]
I had the same trouble on Fedora 27. And after this here is another problem: `ImportError: No module named chardet`.

Solution:
```
sudo python -m pip install chardet
```

**Comment by MeanEYE** [comment]
The issue with `chardet` should have been fixed, but since the fix I didn't make another release. Apologies for that. Good find!

**Comment by joshas** [comment]
@MeanEYE Issue can be closed, as latest develop version of Sunflower runs on Fedora 30 without issues.

**Comment by MeanEYE** [comment]
Okay, thanks!
