### ISSUE TITLE
Can't open any files (file not found)

### ISSUE THREAD

**Issue by inn3rpece** [MeanEYE/Sunflower#273]
I am giving Sunflower 0.3 (61) a go on my Slackware system. However, it does not seem to open anything other than text files and pictures using my text editor and image viewer.

If I right-click an image and click "open with" then my image viewer appears in the list and I can open pictures normally. Double clicking a file works too. I can also open text files normally.

Any other file that requires me to click "open with" and choose an application doesn't work.

Example (all the files do exist on my system):

Opening a spreadsheet with Libreoffice or Calc (in the list) - Libre office shows error:
**/home/paul/"/home/paul/3 May 2017 Pricelist.xlsm" does not exist.**

Opening a pdf with Firefox (in the list) - Firefox shows error:
**file:///home/paul/Downloads/%22/home/paul/Downloads/-1899278134_2017-04-06_12_48_01_0340002489.pdf%22**

Opening a pdf with custom command "xpdf %f" - xpdf shows error:
**I/O Error: Couldn't open file '"/home/paul/Quotation 1041.pdf"'**

Opening a .tar file with custom command "xarchiver %f" - xarchiver shows error:
**Can't open file ""/home/paul/Downloads/php-7.0.17.tar.xz"":
No such file or directory**

Opening .mp3 file with Deadbeef (in the list) - Deadbeef shows error:
**failed to add file or folder "/home/paul/Downloads/earth music.mp3"**

Any help will be appreciated.

**Comment by MeanEYE** [comment]
That's a very strange issue. Never got any reports about such behavior. Can you give me more information about your operating system and Python versions installed?

**Comment by inn3rpece** [comment]
Hi Meaneye,

I'm busy reinstalling to see if I find anything. Please see below:

Slackware 14.2 (x64)
Kernel 4.9.0
120gb SSD, ext4
 
notify-python-0.1.1
pycairo-1.10.0
pygobject-2.28.6
pygtk-2.24.0
python-2.7.11
python-chardet-2.3.0
python-setuptools-22.0.5
python3-3.5.2

**Comment by MeanEYE** [comment]
Which filesystem is this sitting on?

**Comment by inn3rpece** [comment]
ext4. If I use my current file manager, Xfe, then everything works fine.

**Comment by MeanEYE** [comment]
Can you please tell me from where did you install Sunflower?

**Comment by ArseniyK** [comment]
Can confirm it, same errors for "open with" > "Other application" > " use custom command". It look like filepath passed as filename in current directory.

**Comment by inn3rpece** [comment]
I download the Redhat RPM from your website. I then used rpm2tgz which converts the rpm to a slackware package and installed it. rpm2tgz is included in slackware's rpm package.

Strange that Leafpad (text editor) and GPicView (image viewer) is automatically detected by Sunflower and I can double-click a file which then opens. Everything else that doesn't work with a double-click and that requires me to go with "open with" doesn't work.

**Comment by inn3rpece** [comment]
That seems to be the case, which you can see in my first post (the firefox and libreoffice errors).

**Comment by ArseniyK** [comment]
@MeanEYE it hapens here https://github.com/MeanEYE/Sunflower/blob/0.3-gtk2/application/associations.py#L225 shlex.split(exec_string, posix=False) mayby we need use posix=True. Cause posix=False  return ['app', '"filepath"'] instead ['app', 'filepath']

**Comment by inn3rpece** [comment]
Thanks ArseniyK. This fixes the problem on my system.

**Comment by MeanEYE** [comment]
Thanks @ArseniyK. Are there any regressions on other systems?

**Comment by MeanEYE** [comment]
Made the change @ArseniyK proposed and pushed the fix. Packages will be released once I fix the issue with Fedora files not being marked as executable.
