### ISSUE TITLE
Focus lost on delete (check setup)

### ISSUE THREAD

**Issue by rscm** [MeanEYE/Sunflower#277]
Description:
Sometimes (see below) when I delete something the focus (active window) changes
I have to click again on the window to continue
This happen on two versions of sunflower

Setup:
I have a multiple screen setup, and I'm running sunflower on the main one and kodi on the secondary
The main window using DVI and the other one HDMI

Comment:
It doesn't happen if I have another application running on the secondary screen. I've tried with a text editor, for example, and nothing everything is ok.
I can have more than those two applications running (like sunflower+firefox+... | kodi) but is the same outcome if sunflower is in the main and kodi in the secondary

System:
- elementary OS 0.4.1 Loki (Ubuntu 16.04.3 LTS)
- Linux 4.10.0-35-generic
- GTK+ 3.18.9
- sunflower 0.3 (61)
- sunflower 0.2 (59)
- 17.4 Git:20170822-nogitfound Media Center Kodi

What to do to replicate:
- Set two screens
- Open sunflower on the main one and kodi on the secondary fullscreen
- In sunflower, delete a file or directory using the keyboard
- Press a key (an arrow key to move as an example)
- Something will happen on another application (with the arrow key you will navigate on kodi menus) but not on sunflower

**Comment by MeanEYE** [comment]
That's strange and it sounds like a Window manager issue.

Operation windows are not modal as I would like users to have ability to use the program while something is being done in the background.

I'll check if there's something we can do about this.

**Comment by rscm** [comment]
Yes, after several tests with all kinds of combinations I noticed that it is not sunflower. Probably, like you said, the window manager
Sorry the inconvenience, but I just started to use elementary os from another distro and never deleted anything from the gui during the process.

Thanks for the quick answer, bye

**Comment by MeanEYE** [comment]
Okay, thanks for reporting back. Let me know if you don't manage to find solution to this issue. It might be Sunflower after all. All the best!
