### ISSUE TITLE
Selecting a file should not change height of the table row it occupies

### ISSUE THREAD

**Issue by ekaggata** [MeanEYE/Sunflower#280]
Now as I mark a file as selected by right-clicking it or pressing Ins, its table row gets more wide horizontally and all the files below are pushed down. Selecting/deselecting a file should not affect (e.g. move) other rows of the same panel.

**Comment by MeanEYE** [comment]
This shouldn't be the case. Can you please provide some screen shots? Preferably before and after the selection.

**Comment by strangeattr** [comment]
I believe it's about the asterisk added to the right of a marked file name - it's too big.

**Comment by MeanEYE** [comment]
There is a very specific set of conditions that has to be met in order for this behavior to happen. And indeed it is rare to hear such complaint hence the reason why I asked for screen shot. If you can't provide screen shot, can you be specific on which GTK+ theme and icon theme you are using?

As for asterisk itself, Sunflower does allow you to change it or entirely disable it if you so desire. In _Preferences_ window under _Item List_ there's an option named _Selection indicator_. While it's a drop down list it can also be edited and you can put anything there.

**Comment by strangeattr** [comment]
Here is the screenshot: [https://imgur.com/a/HnCEX](https://imgur.com/a/HnCEX)
The table row is 1 pixel bigger in the second case. This may seem futile but it feels a little bit annoying as it sets all the files below in motion when I'm selecting files. I would mark it as a low-priority bug. I am using Ubuntu 16.04 LTS with the default theme.

**Comment by MeanEYE** [comment]
Okay, this might be GTK+ issue then but I will keep it open and accepted. We are in the middle of the switch to GTK3 which should do away with problems like these. Some of the column rendering had to be done with custom widget and all kinds of dark magic in GTK2.

**Comment by MeanEYE** [comment]
This issue is no longer reproducible on GTK3 version of the program.
