### ISSUE TITLE
Config Option: default operation queue to None

### ISSUE THREAD

**Issue by uhbif19** [MeanEYE/Sunflower#289]
I never use operation queues, but on every operation must choose None. Please add config option to use None by default, without popup dialog.

**Comment by MeanEYE** [comment]
Can you be specific about version you are using?

**Comment by uhbif19** [comment]
I use "Sunflower 0.3 (61)", as says "About" window.

**Comment by MeanEYE** [comment]
Which desktop environment? Since I am unable to reproduce the same behavior on my machine.

**Comment by uhbif19** [comment]
I am not sure if I expressed clearly. It is not a bug, but a feature request.

Now I see this dialog on every (removal from example) operation. But I want some option to disable this behavior, because I never use any operation queues.

![2018-01-22-023003_1366x768_scrot](https://user-images.githubusercontent.com/300919/35200297-75802a6c-ff1c-11e7-8f1a-7614f2ed13ce.png)

**Comment by MeanEYE** [comment]
Ah, okay. That's a different matter then all together. It's not a problem of adding a new configuration option for this but I wonder if there are benefits user can experience from such option? Can you give a little bit more information behind such desire to remove them? Are you clicking on them by accident or something else? Or is it just a visual thing?

**Comment by MeanEYE** [comment]
Switch to GTK3 solved this issue as all the queues are now in the header bar and for that reason are not getting default focus.
