### ISSUE TITLE
could it works in raspberry ?? 

### ISSUE THREAD

**Issue by testphoto** [MeanEYE/Sunflower#290]
I have downloaded gtk 3.0 for raspberry and tried to run the app but did not work.
it show me that missing GTK 3.0

**Comment by MeanEYE** [comment]
GTK+ 3 version is really broken at this point. Once fixed and released minimum version required will be 3.20, since at that point developers stabilized API. Previous version of Sunflower 0.4 (61) should work without a problem but it's using GTK 2.x.

**Comment by testphoto** [comment]
thanks

**Comment by MeanEYE** [comment]
You are welcome.

**Comment by MeanEYE** [comment]
New version which is being prepared is going to use _GObject Introspection_ and with it GTK3 which is mature enough on all versions. This includes RaspberryPi. Am closing this issue as current version should already on it. Please reopen if upon release there are additional problems!
