### ISSUE TITLE
About go to up folder

### ISSUE THREAD

**Issue by r91085** [MeanEYE/Sunflower#295]
Is it possible to disable full row selection , and let me can double click right mouse button to go to up folder ?

Some file manager in windows platform has this feather , and I feel it is very convenient .

**Comment by MeanEYE** [comment]
I don't see why would full row selection prevent you from double-clicking right mouse button?

**Comment by r91085** [comment]
Oh , I was wrong , it should be left mouse button

**Comment by MeanEYE** [comment]
Can you describe this behavior in more details and why is row selection in the way? You can already double-click on `..` to go up one level.

**Comment by r91085** [comment]
Yes , I can double click ".."  go up one level.

But sometimes I browser the files of one directory and move up and down in the file pannel. The ".." is the first item , I must move to the top of panel to click it .

If I can just double click at the blank of the panel to go up , it will be faster. In windows platform , some file explorer application disable full row selection , you only can select file by clicking the name column . So I can just double click on other column area like size , date ..etc to go up one level rather than select the item.

Another behavior under this kind of design is that the mouse right click menu has two type. If you right click on the file name (it means you select it) , the popup menu will be some operation only about the file. If you right click on the other area , it will popup the menu about this directory , mabye create file , create folder or paste ...

**Comment by r91085** [comment]
Yes , I can double click ".."  go up one level.

But sometimes I browser the files of one directory and move up and down in the file pannel. The ".." is the first item , I must move to the top of panel to click it .

If I can just double click at the blank of the panel to go up , it will be faster. In windows platform , some file explorer application disable full row selection , you only can select file by clicking the name column . So I can just double click on other column area like size , date ..etc to go up one level rather than select the item.

Another behavior under this kind of design is that the mouse right click menu has two type. If you right click on the file name (it means you select it) , the popup menu will be some operation only about the file. If you right click on the other area , it will popup the menu about this directory , mabye create file , create folder or paste ...

**Comment by MeanEYE** [comment]
Am not liking this idea as it is not intuitive to users. We would have to educate them somehow and tell them these features exist. 

However, next version will have path in the tab titlebar clickable. So you will be able to go any position along the path. Would such behavior be good for you? It's significantly simpler and more intuitive to have path fragmented and allow clicking on each element.

**Comment by r91085** [comment]
I am not very sure I understand what you mean totally.

Now in Sunflower every tab panel has it's own clickable path , so I don't really understand what is difference between "path in the tab titlebar clickable" and the now design.

I am using windows platform for a long time , the operator  I said before existed in many tab FileManager.  I am new in Linux , and mabye it is not intuitive to linux users . And in forum of DoubleCommand there is antoher user asking this feature , I think he is go from windows platform like me : )

Mabye you are right , user must be told here is some kind of feature . But if this kind of operator can really speedup the working flow. Why not giving it a try ?

A little thought , never mind : )  Waiting for next version

**Comment by MeanEYE** [comment]
Am not against adding it as a feature, but mostly trying to make operations intuitive and easy to learn on its own. Adding this would be a fairly simple job.

What I was referring to was to implement bread crumbs for path like Nautilus does:
![screenshot from 2018-03-29 09-35-54](https://user-images.githubusercontent.com/1911594/38073655-a6cf2b1c-3334-11e8-8b3e-339da69a3a5f.png)

In fact we already support them but they will have to change for next version.

By using bread crumbs you can navigate to any parent path with just a single click and be able to return to previous paths. To me this is much more intuitive than double clicking on empty space, and disabling row selection, etc.
