### ISSUE TITLE
Missing icons under KDE

### ISSUE THREAD

**Issue by and-semakin** [MeanEYE/Sunflower#297]
I am running Sunflower under KDE 5 Plasma and some icons are missing.
![screenshot_20180408_165640](https://user-images.githubusercontent.com/9129071/38467182-19d4f0f8-3b4e-11e8-85a4-a32ec93043d2.png)
```
$ plasmashell --version
plasmashell 5.12.4
$ kf5-config --version
Qt: 5.9.4
KDE Frameworks: 5.44.0
kf5-config: 1.0
```

**Comment by MeanEYE** [comment]
We use GIO to derive icon names. Functions GIO has return a list of names, but it looks like these are not tested for existence. Basically what's happening here is that you are missing GTK configuration which tells it which icon theme to use.

You should be able to get around this by modifying `~/.gtkrc-2.0` and adding the following line:

```
gtk-icon-theme-name="Icon-Theme-Name"`
```

**Comment by BrokeRU** [comment]
Do I need to replace `Icon-Theme-Name` with my icon-theme-name or just put this line exactly? Sorry for my noobish questions.

**Comment by MeanEYE** [comment]
You need to replace it with your icon theme. It's not a noobish question, I should have explained that.
