### ISSUE TITLE
Dont Open on Ubuntu 18.10

### ISSUE THREAD

**Issue by mirkosamir** [MeanEYE/Sunflower#305]
Clean install Ubuntu 18.10 , sunflower crash 

Sunflower 0.3 | build 61

Log
failed to rescan: Failed to parse /usr/share/applications/sunflower.desktop file: cannot process file of type application/x-desktop
[log messages.txt](https://github.com/MeanEYE/Sunflower/files/2496759/log.messages.txt)

-----
Console output:
mirko@Rommel:~$ sunflower
Traceback (most recent call last):
  File "/usr/share/sunflower/application/main.py", line 31, in <module>
    from gui.main_window import MainWindow
  File "/usr/share/sunflower/application/gui/main_window.py", line 31, in <module>
    from plugin_base.item_list import ItemList
  File "/usr/share/sunflower/application/plugin_base/item_list.py", line 11, in <module>
    from tools.viewer import Viewer
  File "/usr/share/sunflower/application/tools/viewer.py", line 2, in <module>
    import chardet
ImportError: No module named chardet
Failed running with python2.7

**Comment by MeanEYE** [comment]
You are missing `python-chardet` module. I messed up dependencies, thanks for reporting!

**Comment by mirkosamir** [comment]
Perfect.
in case someone need to solve quickly, install de module:

sudo apt-get install python-chardet

**Comment by STEPHEN-GOLDBOROUGH** [comment]
Also in Mint 19.1 I got the program to work by installing 'python-chardet'. One further issue was then that the terminal tab was blank with a "couldn't find python v t e" message. So I had to install python vte using synaptic package manager, Now the tab is working :)

**Comment by MeanEYE** [comment]
Python VTE module is indeed optional, perhaps option should automatically disable if no terminal is available or to make the package required.

**Comment by MeanEYE** [comment]
New version at any case will reuse many of the system's dependencies through GI.

**Comment by MeanEYE** [comment]
This issue is fixed on new version.
