### ISSUE TITLE
Folders with >100 items are crashing Sunflower

### ISSUE THREAD

**Issue by awaken1ng** [MeanEYE/Sunflower#306]
Playing around with @tjol's Python 3 branch in #304, I first noticed that opening my home directory was crashing Sunflower, after changing some of the settings, it seemed that `Show hidden files` was causing it, but on further testing it seems that any folder with more than 100 items in it (folders and/or directories) will crash Sunflower.

Also happens on `develop` branch, although it doesn't seem to always crash immediately. After moving up and down a little, folders (and probably files) start to duplicate, rapidly moving up and down using breadcrumbs will crash the application. [Sometimes starts spewing out Gtk errors left and right.](https://gist.github.com/awaken1ng/f0dcde58ec041e94cf35f153f2586d76)

After briefly testing the `master` branch, doesn't seem to be a problem there.

Typically crashes with `Gtk:ERROR:gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))` error.

Antegros 4.18.14-arch1-1-ARCH
Python versions are 3.7.0-4 and 2.7.15-2
gtk3 version is 3.24.1+8+g22
python-gobject and python2-gobject versions are 3.30.1-3

**Comment by tjol** [comment]
As far as I can tell, this is a multithreading issue. GtkTreeStore is not thread-safe, and `FileList._flush_queue` is called both from the main thread and from the directory loading thread. This is true especially when https://github.com/MeanEYE/Sunflower/blob/d4a6abc6d77e5caed587712354af01497e0c20ac/sunflower/plugins/file_list/file_list.py#L1717 comes into play.

Properly synchronising treestore modifications in way that doesn't impact performance will take some finesse.

**Comment by awaken1ng** [comment]
[Stumbled on this](https://wiki.gnome.org/Projects/PyGObject/Threading), and tried replaced
https://github.com/MeanEYE/Sunflower/blob/d4a6abc6d77e5caed587712354af01497e0c20ac/sunflower/plugins/file_list/file_list.py#L1718
with `Gdk.threads_add_idle(self._flush_queue, parent)`, the crashing stopped.

**Comment by tjol** [comment]
> I forgot to revert some changes I made earlier and I'm calling the function improperly, the proper way is `Gdk.threads_add_idle(GLib.PRIORITY_DEFAULT_IDLE, self._flush_queue, parent)`, which made it crash again, but wrapping all `self._flush_queue` calls stopped it, not sure whether that achieved anything useful though.

Pushing all calls to _flush_queue into the main thread like this will work, but when I tried this made loading of large directories feel a lot slower.

**Comment by MeanEYE** [comment]
Okay, first sorry for lack of communication, hectic working schedule. Anyway, whole idea behind _flush_queue was for it to happen in the main thread. Unfortunately GTK+ is not thread safe so we have to do that from the main/UI thread. Perhaps the value of maximum elements in the queue should be tweaked. This is code that remained from GTK2 version and perhaps is not good enough for the new version.

Whole idea is not to allow interface to freeze while data is being loaded. Slow loading times could be a factor of something else but Sunflower is not excluded from that list.
