### ISSUE TITLE
Crash before appearing any window

### ISSUE THREAD

**Issue by RafaelLinux** [MeanEYE/Sunflower#307]
OpenSUSE 15 - Sunflower RPM official (http://sunflower-fm.org/pub/sunflower-0.3.61-1.noarch.opensuse.rpm)

After install, if I launch from desktop, nothing happens.
If I launch from console, it shows this errors:
```
/usr/bin/s/usr/bin/sunflower: line 3: /usr/share/sunflower/Sunflower.py: Access denied
/usr/bin/sunflower: line 3: exec: /usr/share/sunflower/Sunflower.py: can't execute: Access denied
```
Even if II launch with "sudo sunflower", result is the same, and the same if I change "/usr/bin/s/usr/bin/sunflower" propietary to my user and group.
:(

**Comment by MeanEYE** [comment]
Sorry for that. It's an issue with RPM package I made. Just do `sudo chmod +x /usr/share/sunflower/Sunflower.py`. That should do it. Let me know if you have issues with this after that command and I'll help resolve it.

Am going to leave this issue open so people can find it. And am going to find some time in upcoming days to fix it.

Thanks for reporting!

**Comment by RafaelLinux** [comment]
I uninstalled sunflower, removed the directory where was installed (/usr/ ....) , installed it again and finally I did the change to make it executable, but unfortunately, only changed the error messages ....
`Traceback (most recent call last):

  File "/usr/share/sunflower/application/main.py", line 31, in <module>
    from gui.main_window import MainWindow
  File "/usr/share/sunflower/application/gui/main_window.py", line 31, in <module>
    from plugin_base.item_list import ItemList
  File "/usr/share/sunflower/application/plugin_base/item_list.py", line 11, in <module>
    from tools.viewer import Viewer
  File "/usr/share/sunflower/application/tools/viewer.py", line 2, in <module>
    import chardet
ImportError: No module named chardet
Failed running with python2.7`

So no luck on giving a try to Sunflower.

:(

**Comment by MeanEYE** [comment]
This issue should be fixed in new version now.
