### ISSUE TITLE
[Translation]: Add a file for Japanese translation

### ISSUE THREAD

**Issue by cmplstofB** [MeanEYE/Sunflower#309]
Hello.
I want to translate the Sunflower project into Japanese.
The project language "Japanese (Japan)" have already been accepted [on Transifex](https://www.transifex.com/way2cu/sunflower/).
However, I cannot join the translation team because the Sunflower project has no files for Japanese translation.
Could you please add `ja_JP/LC_MESSAGES` directory and `sunflower.po` file under [`translation` directory](https://github.com/MeanEYE/Sunflower/tree/develop/translations) so that I can start to translate?

Thank you.

**Comment by MeanEYE** [comment]
Of course.

**Comment by MeanEYE** [comment]
Done.

**Comment by cmplstofB** [comment]
Thank you!

**Comment by MeanEYE** [comment]
You are most welcome. Thank you for providing Japanese translation.
