### ISSUE TITLE
breadcrumbs use more space than they should

### ISSUE THREAD

**Issue by tjol** [MeanEYE/Sunflower#311]
The location breadcrumbs always display the full path, even when the path is too long to fit. This leads to the panel width growing to accommodate the path in a deeply nested directory structure.

**Comment by MeanEYE** [comment]
This was in my plan to fix and there are some local changes which I haven't pushed yet. Merge request probably conflicts with some of that code. I'll have to review and see how I can make it work.

**Comment by joshas** [comment]
Issue was resolved by commit https://github.com/MeanEYE/Sunflower/commit/d854315287bb9c1f7db60b64159e301fd6a533fe

**Comment by joshas** [comment]
@MeanEYE Just a reminder that issue can be closed.

**Comment by MeanEYE** [comment]
Thank you @joshas !
