### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by yuuki0xff** [MeanEYE/Sunflower#315]
The latest release (v0.3-61) is about 3 years ago.  Would you please release a new version?

**Comment by MeanEYE** [comment]
New version is being planned and worked on. Next release will be using GTK3 which took far longer than I anticipated since a lot of old interface is being rebuilt. In addition to that my work got in the way. So yes, new version is planned and I hope that will happen soon. Thanks for taking the time to report this even though it's not really a valid issue, I will leave it open to keep reminding me.

**Comment by cebas** [comment]
I do like SunFlower, but 3 years without releases seems like an abandoned project. Please, don't!
Consider finding some help from the community.
Cheers

**Comment by MeanEYE** [comment]
Oh, I am by no means abandoning this. But you are right, new release is long overdue, I will try to make it happen. Feel free to remind me :) frequently...

**Comment by MeanEYE** [comment]
![image](https://user-images.githubusercontent.com/1911594/52570250-392cbb80-2e13-11e9-827e-614ce12d526f.png)
This is how it currently looks. But I am not done with unified locations menu. Some other popup menus need to be fixed as well.

Perhaps I could start doing weekly releases of this version until it's done. It's fairly stable, but lacks polish in many areas and community can help iron those out.

**Comment by cebas** [comment]
> Oh, I am by no means abandoning this. But you are right, new release is long overdue, I will try to make it happen. Feel free to remind me :) frequently...

First reminder ;-)

**Comment by slashbeast** [comment]
@MeanEYE Since you're about to release new version, would you consider semantic versioning? Having 0.2-59 and 0.3-61 is a bit hard to maintain on the distribution end.

**Comment by MeanEYE** [comment]
@slashbeast I am contemplating of making this version 1.0. Sunflower has been out for a decent amount of time and despite its drawbacks it is fairly stable. Of course it will sit on 1.0 beta for a while until I flesh out new version. This would also be a perfect opportunity to switch to such versioning method.

**Comment by kobylyanets** [comment]
Can we expect a release this year?

**Comment by MeanEYE** [comment]
You can. Even though development looks slow at this point it is my intention to move on with next version as soon as my free time allows it.
-- 
Mladen Mijatov
Head of R&D, Way2CU

Key ID: 4096R/83EFD5A0 2013-08-18

**Comment by r03** [comment]
Second reminder :-) 
I understand this is just an hobby project, so no pressure.

**Comment by MeanEYE** [comment]
Thanks :)... I actually started moving a little bit with hobbies, Sunflower included. Recently one of my big issues was solved. Reminder is very welcome and am glad there is still interest in this project.

**Comment by dkebler** [comment]
I need a stand alone gnome3 or qt5 based minimal dependency file manager for xll forwarding from arm64 sbcs.  I like nemo but later versions are now tied to the cinnamon desktop and rendering desktop icons etc. So I'm on the lookout for a good features alternative that I can compile for arm64.  I've tried compiling several that are maintained with disappointment including newbreeze.  Caja is one that runs ok direct from aarch64 bionic universe albiet it's the way behind version.  So I'm watching for your next release!   

FYI, one can cross compile easily enough for arm64 using a docker container.  Once you have a working Dockerfile banging out an arm64 version at each release is easy. An appimage file is good but even better would be in addition a debian/ubuntu deb or better yet an ubuntu ppa so updating is easy (bionic is now the go to linux for most capable sbcs).  So if you make a point of rendering a compilation for arm64 I and many others would be all over it.

**Comment by joshas** [comment]
How about splitting v0.4 milestone into a few smaller milestones and starting releasing Beta versions?

**Comment by MeanEYE** [comment]
I think v0.4 milestone is going to be split in few more. Everything until 1.0 I consider beta, so going for 0.4 beta, 0.5 beta, etc. is kind of redundant. But I definitely need to start releasing more often. Ideally bi-monthly or something like that. So I'll schedule 0.4 for next Sunday, and push out a version regardless of its state.

Things that got broken will be fixed for next one, etc.

**Comment by MeanEYE** [comment]
Done :)
