### ISSUE TITLE
Window size on first start is too small

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#316]
When starting Sunflower for the first time, application window is too small. It should have reasonable default size, e.g. 800x600.

![window-sizing](https://user-images.githubusercontent.com/79141/55670400-61bdb880-588c-11e9-8d6b-b7e9cd2ea61e.png)

Tested latest Sunflower version from develop branch, on Ubuntu 19.04 Beta.

**Comment by MeanEYE** [comment]
Thanks. I'll fix that.
