### ISSUE TITLE
Application menu migration to primary menu

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#317]
With [recent deprecation of App Menu](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement) Sunflower app menu is missing on Ubuntu 19.04 (Beta). It should be migrated to primary menu on toolbar.

**Comment by MeanEYE** [comment]
I thought they would manually migrate the menus which now doesn't seem to be the case. I will fix this. Thanks for reporting.

**Comment by joshas** [comment]
Looks like this issue can be closed, as commit f9fdcbf005e69da66e6ffb2b8a08977f146006ad added primary menu.

**Comment by MeanEYE** [comment]
Yeah. Thanks. Forgot about this issue :)
