### ISSUE TITLE
Copy path to clipboard function doesn't work

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#318]
Clicking "Copy path to clipboard" from "Context menu" doesn't work. It results in following error:

> Traceback (most recent call last):
  File "/home/virtualbox/work/Sunflower/sunflower/plugin_base/item_list.py", line 1525, in copy_path_to_clipboard
    self._parent.set_clipboard_text(self.path)
  File "/home/virtualbox/work/Sunflower/sunflower/gui/main_window.py", line 2648, in set_clipboard_text
    self.clipboard.set_text(text)
TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)

Tested latest Sunflower version from develop branch, on Ubuntu 19.04 Beta.

**Comment by MeanEYE** [comment]
This is a change in GTK+ API from version 2.x to 3.x. Thanks for reporting.

**Comment by MeanEYE** [comment]
Fix for this particular issue is easy to solve however there's a bigger issue regarding clipboard integration. GTK+ developers managed [not to fix this bug with introspection for past 8 years](https://gitlab.gnome.org/GNOME/gtk/issues/364) basically preventing any Python developer from using clipboard for any other purpose other than copying text.

I will leave this issue open as a reminder why we can't implement clipboard support properly. To solve this issue I will have to come up with a different, more creative, solution which doesn't rely on GTK+ for clipboard.
