### ISSUE TITLE
Commands list is empty

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#319]
After adding custom commands in Preferences and saving, "Commands" menu in header bar remain empty. Commands are listed in main menu and are saved in commands.json settings file.

Problem is that `_create_commands_menu` function in main_window.py clears `commands_menu` (one in header bar), but adds items to `menu_commands` menu (one in Main menu).

**Comment by MeanEYE** [comment]
One of the features that didn't get remade yet. Thanks for reporting.

**Comment by joshas** [comment]
Issue was resolved by commit https://github.com/MeanEYE/Sunflower/commit/2b03555b6cdec482abf600017f4561e87912bee7
