### ISSUE TITLE
Multiple copies of same file added when saving in external editor

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#323]
Create new text file. Open that file in external text editor. Now try editing this file and save it often. File list will add a new copy of the same file after each save.

![duplicate-files](https://user-images.githubusercontent.com/79141/55685482-8898ef00-595f-11e9-8706-38c55c5f8165.png)

**Comment by MeanEYE** [comment]
Noticed this as well. Probably something different in Gio monitoring API since last version.

**Comment by MeanEYE** [comment]
This is really odd. GEdit in question here does some really weird things. This is the output of directory monitor just when pressing "save":
![image](https://user-images.githubusercontent.com/1911594/61178678-f81f1a00-a5f1-11e9-8da3-eeea8d251100.png)

What happens is that file is created, messed around with, then moved around, changed again and moved once more. Different editors behave differently, but it's a really odd way of approaching simple file save.

**Comment by MeanEYE** [comment]
Hm, they changed behavior from different GIO versions. Odd, but new functionality should cover future cases.
