### ISSUE TITLE
Issues with URLs in credits

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#331]
In About -> Credits URL after author email is displayed without space before it. Also, if URL has no protocol (http://) - it is not clickable.
![about-url-1](https://user-images.githubusercontent.com/79141/60363277-c13ee680-99eb-11e9-81e1-91fbc97f9569.png)
![about-url-2](https://user-images.githubusercontent.com/79141/60363280-c308aa00-99eb-11e9-9a7e-26d17bf8b628.png)

Quick look at GTK About Dialog documentation gave me impression that you can either have email or URL, but not both. Otherwise you'd need to customize URL replacement functions.

**Comment by MeanEYE** [comment]
Thanks!
