### ISSUE TITLE
Version check doesn't work

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#334]
Opening Help -> Check for new version dialog results in following error:

> Exception in thread Thread-3:
Traceback (most recent call last):
  File &quot;/usr/lib64/python3.7/threading.py&quot;, line 917, in _bootstrap_inner
    self.run()
  File &quot;/usr/lib64/python3.7/threading.py&quot;, line 865, in run
    self._target(*self._args, **self._kwargs)
  File &quot;/home/virtualbox/dev/Sunflower/sunflower/tools/version_check.py&quot;, line 85, in __threaded_check
    releases = decoder.decode(data)
  File &quot;/usr/lib64/python3.7/json/decoder.py&quot;, line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: cannot use a string pattern on a bytes-like object

**Comment by MeanEYE** [comment]
Thanks for reporting this. It's most likely when we switched from Python 2 to 3.
