### ISSUE TITLE
Help -> Homepage does nothing

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#335]
Clicking Help -> Homepage results in error:

> Traceback (most recent call last):
  File &quot;/home/virtualbox/dev/Sunflower/sunflower/gui/main_window.py&quot;, line 1859, in goto_web
    if &apos;://&apos; in uri:
TypeError: argument of type &apos;NoneType&apos; is not iterable

**Comment by MeanEYE** [comment]
Thanks for reporting this!
