### ISSUE TITLE
Zipped files without dates are not displayed

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#336]
In very rare cases I have to deal with zip files where zipped contents have no dates set. Other file managers, like mc, display files, but add some old dates to them. unzip -l shows dates as "00-00-1980 00:00".
In Sunflower such files in zip are not displayed at all, error message in terminal:

> Load directory error:  month must be in 1..12

**Comment by MeanEYE** [comment]
Didn't know this was a possibility. Thank you for reporting this.

**Comment by MeanEYE** [comment]
Thank you for your contribution. It's much appreciated.
