### ISSUE TITLE
Will classic menu be removed?

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#340]
Currently in main_window.py there is code for classic menu, but it is disabled: https://github.com/MeanEYE/Sunflower/blob/develop/sunflower/gui/main_window.py#L727
Is it going to be removed in the future? If so, what's the plan of migrating menu entries to header bar?

**Comment by MeanEYE** [comment]
Yes. Plan is to migrate it to new application menu. I left the code there
but disabled because it needs to be reimplemented in a new way.

**Comment by joshas** [comment]
Got it. Let's keep discussion about application menu migration in #317 .
