### ISSUE TITLE
Drag and Drop support for external applications

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#345]
Add support for dragging and dropping files to and from other applications, e.g. browser, image editor, other file managers, etc.

**Comment by MeanEYE** [comment]
This use to work but got broken in switch to GTK3.

**Comment by joshas** [comment]
Looks like it is working again. Thank you.

**Comment by MeanEYE** [comment]
Good to know. Thank you for testing and closing the issue.
