### ISSUE TITLE
Toolbar button ordering issue

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#352]
Add some buttons to toolbar, save and relaunch Sunflower. Now toolbar buttons are re-ordered alphabetically.
Problem is in toolbar.json config file, as button names are used as object keys and storing config re-orders them. There's also a potential to name button as toolbar config option and get some interesting results. Toolbar button items in config should probably be moved to array.

**Comment by MeanEYE** [comment]
Thank you!
