### ISSUE TITLE
Copy, cut, paste files not working

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#357]
Due to GTK3 limitations clipboard operations (copy, cut and paste) on files are not working. More details in this comment https://github.com/MeanEYE/Sunflower/issues/318#issuecomment-480585139 

Maybe we should look into how clipboard operations are implemented in Gnome Files and other GTK3 applications? Maybe error messages can help finding replacements for deprecated functions?

Error messages for future reference:

Copy
> Traceback (most recent call last):
>   File "/home/virtualbox/dev/Sunflower/sunflower/plugin_base/item_list.py", line 887, in _copy_files_to_clipboard
>     self._parent.set_clipboard_item_list(operation, selected_items)
>   File "/home/virtualbox/dev/Sunflower/sunflower/gui/main_window.py", line 2697, in set_clipboard_item_list
>     return self.clipboard.set_with_data(targets, get_func, clear_func)
> AttributeError: 'Clipboard' object has no attribute 'set_with_data'

Cut
> Traceback (most recent call last):
>   File "/home/virtualbox/dev/Sunflower/sunflower/plugin_base/item_list.py", line 871, in _cut_files_to_clipboard
>     self._copy_files_to_clipboard(operation='cut')
>   File "/home/virtualbox/dev/Sunflower/sunflower/plugin_base/item_list.py", line 887, in _copy_files_to_clipboard
>     self._parent.set_clipboard_item_list(operation, selected_items)
>   File "/home/virtualbox/dev/Sunflower/sunflower/gui/main_window.py", line 2697, in set_clipboard_item_list
>     return self.clipboard.set_with_data(targets, get_func, clear_func)
> AttributeError: 'Clipboard' object has no attribute 'set_with_data'

Paste
> Traceback (most recent call last):
>   File "/home/virtualbox/dev/Sunflower/sunflower/plugin_base/item_list.py", line 893, in _paste_files_from_clipboard
>     data = self._parent.get_clipboard_item_list()
>   File "/home/virtualbox/dev/Sunflower/sunflower/gui/main_window.py", line 2706, in get_clipboard_item_list
>     selection = self.clipboard.wait_for_contents('x-special/gnome-copied-files')
> TypeError: argument target: Expected Gdk.Atom, but got str

**Comment by MeanEYE** [comment]
When copying files into clipboard we need to set type of data as well. Issue here is that function that does that is not available to Python due to broken Introspection files. I contacted developers and they said nothing about that.

**Comment by MeanEYE** [comment]
Additional information regarding this issue. Function in question that is missing is [`set_with_data`](https://developer.gnome.org/gtk3/stable/gtk3-Clipboards.html#gtk-clipboard-set-with-data) which doesn't exist in Python bindings due to parameter type being incompatible if I remember correctly. I currently don't know a workaround for this. Some additional tests could be performed to see if we can get away with using regular `set_text`, or some other method.

**Comment by MeanEYE** [comment]
Over-engineered solution was made but it works. Basically framework for providers was created where they are used in descending order of usefulness. We start with plain GTK then move on to command line tools like `wl-clipboard` and `xclip`, then we have fake clipboard which keeps functionality working within application.

For any wondering developers bashing their head into ground and thinking how the hell do you copy and paste files with Nautilus, the answer is simple. They have changed the way clipboard works. It use to be set with `set_with_data` where target would be `x-special/gnome-copied-files` but it's no longer that.

Neither `set_with_data` nor mime type are the same. If you wish to copy/paste stuff from clipboard and have Nautilus pick it up, all you need to do is call `set_text` with following format:

```
x-special/nautilus-clipboard
copy
file://...
file://...

```
Operation can be either `copy` or `cut`, and trailing newline is _MANDATORY_. That's it.
