### ISSUE TITLE
Unmount not working in locations popover

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#363]
Clicking "Unmount" button in Locations popover does nothing. USB flash drive was not unmounted, no errors.

**Comment by MeanEYE** [comment]
Locations menu is still not complete. So this is the reason. It simply does nothing at the moment.

**Comment by joshas** [comment]
I see that unmount functionality was added in c82d745c4280853387edc7b2fe2f83b74bc24fc9 . Thank you.

**Comment by MeanEYE** [comment]
You are welcome. There are still odd behaviors which I need to iron out. MTP volumes being one of them. Regular drives work fine, but MTP for some reason shows as unable to be ejected but as unmounted as well, even though it is mounted.

**Comment by joshas** [comment]
MTP protocol is a bit odd, as it does not require actual unmounting.

> File transfers are atomic, and no explicit filesystem unmounting (“safe removal”) is required of the user. [source](https://en.wikipedia.org/wiki/Media_Transfer_Protocol#File_oriented_instead_of_block_oriented_protocol)

**Comment by MeanEYE** [comment]
Am aware of that as that was its main advantage over initial approach Android had. However with Sunflower state ends up being in a state where it shows mount option but no unmount or eject. Nautilus as comparison has eject or unmount option (they use the same icon).

**Comment by MeanEYE** [comment]
That's the behavior am talking about fixing.
