### ISSUE TITLE
"Show right bookmarks" default hotkey not working

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#364]
While Ctrl + F1 opens up left bookmarks popover, pressing Ctrl + F2 does nothing. Because I can set Ctrl + F2 as shortcut in Preferences, it probably is an internal problem with Sunflower itself, not desktop environment eating up inputs. Tested on Fedora 30 with GNOME 3, if that matters.
If I press Ctrl + F2 while right panel is focused - "Rename file/directory" modal opens. If I set "Show right bookmarks" hotkey to Ctrl + F11 - right popover opens up correctly. Could it be that Fn hotkeys override hotkeys with Ctrl modifier?

**Comment by MeanEYE** [comment]
I have already ran into this issue and have tried solving it. Sadly I don't know if we can fix this one.

To further test this issue I have created a small [test](https://pastebin.com/EWrAzvK5). If you run it you will see that `AccelGroup` simply doesn't like modifies on function keys. Everything else seems to be running fine.

Sad thing is I tried asking GTK+ developers, but they've been spinning me in circles. One place directed me to other, they to some other, etc. Reporting an issue is getting challenging.

**Comment by joshas** [comment]
Problem occurs only using Wayland. In Xorg hotkeys work correctly: in your demo and in Sunflower.

**Comment by MeanEYE** [comment]
That is very interesting. This is most likely Gnome's fault, not so much display manager/protocol. That is very good to know. I've spent hours trying to fix this with many different approaches and nothing worked.

Thanks for testing. This one looked like it was going to be a huge pain to fix, but we just need to report upstream. Where to report is a different thing.
