### ISSUE TITLE
Does not run on Fedora 31

### ISSUE THREAD

**Issue by dreamstorpi** [MeanEYE/Sunflower#367]
Looks like same issue as #269, but that issue is closed, so I'm creating a new issue

I just downloaded and installed on Fedora 31, 03 december 2019

I got this message
/usr/share/sunflower/Sunflower.py: Permission denied
which I fixed with,
chmod +x /usr/share/sunflower/Sunflower.py

I then got this message
No module named chardet
Failed running with python2.7

I tried using pip to install chardet but got a message saying it was already available.
Fedora 31 comes with Python 3.7.5

Do you have any solution for this?

**Comment by MeanEYE** [comment]
These are all known issues which I thought were fixed. Sadly it doesn't seem like that's the case. First of them is RPM issue, which is fixed like you said. Second one is missing dependency but we are not using Python3 in that version. So you can install `python-chardet` or `python2-chardet`. Python3 version is in the works and these issues will be fixed. Sorry for the inconvenience.

I will leave this issue open so others find it as well.

**Comment by dreamstorpi** [comment]
Thanks for your reply MeanEYE.
For the record, I installed python2-chardet and it now works on Fedora 31.

**Comment by MeanEYE** [comment]
New version should have this fixed. Please reopen if it's not.
