### ISSUE TITLE
setup.py: support installation

### ISSUE THREAD

**Issue by slashbeast** [MeanEYE/Sunflower#371]
Currently sunflower cannot be installed as regular Python module. The current list of dependencies list non-pypi packages, the chardet and gi (pygobject) modules are not included in the list, and even after installing it without those non-pypi deps it does not start:

```% sunflower
Traceback (most recent call last):
  File "/home/piotr/tmp/venv/lib/python3.7/site-packages/sunflower/__main__.py", line 174, in do_activate
    dont_load_plugins=self.arguments is not None and self.arguments.dont_load_plugins
  File "/home/piotr/tmp/venv/lib/python3.7/site-packages/sunflower/gui/main_window.py", line 85, in __init__
    self._load_styles()
  File "/home/piotr/tmp/venv/lib/python3.7/site-packages/sunflower/gui/main_window.py", line 1187, in _load_styles
    provider.load_from_file(Gio.File.new_for_path(file_name))
gi.repository.GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /home/piotr/tmp/venv/bin/styles/main.css: No such file or directory (2)
```
Without working setup.py it's almost impossible to package this into distribution without bending over backward.

**Comment by MeanEYE** [comment]
We are working on this functionality still. It first started as an attempt to make a standalone executable, then it progressed to migration to Python3 and moved on to supporting distutils. I am however unfamiliar with this way of installation and online documentation doesn't seem too helpful.

My goal is to support packaging using this method.

Are you familiar with some documentation I can look up in regards to properly writing `setup.py`? There are few static files which we need and in addition to that we need some system packages which shouldn't be pulled from PyPI.

**Comment by MeanEYE** [comment]
This should be fixed now. However it's still not complete as `.desktop` file is not being installed. Please retest and let me know if this issue is now fixed.

**Comment by slashbeast** [comment]
Hi,

It did not worked out of the box as it was failing to find images, but
here's quick fix, not sure if it's the best way to do it, but it does work.

```
diff --git a/setup.py b/setup.py
index 74e4693..1e0c148 100644
--- a/setup.py
+++ b/setup.py
@@ -25,10 +25,9 @@ setup(
 			],
 		packages=find_packages(),
 		include_package_data=True,
-		data_files=[
-			('images', ['images/sunflower.svg']),
-			('images', ['images/splash.png']),
-			('share/applications', ['Sunflower.desktop'])
-			],
+                data_files=[
+                    ('share/sunflower/images/',
['images/sunflower.svg', 'images/splash.png']),
+                    ('share/applications', ['Sunflower.desktop'])
+                ],
 		entry_points={'console_scripts': ['sunflower = sunflower.__main__:main']}
 		)
diff --git a/sunflower/icons.py b/sunflower/icons.py
index f43537e..892487e 100644
--- a/sunflower/icons.py
+++ b/sunflower/icons.py
@@ -132,6 +132,6 @@ class IconManager:

 		# load from local path
 		else:
-			base_path = os.path.dirname(get_base_directory())
+			base_path = os.path.join(sys.prefix, 'share', 'sunflower')
 			window.set_icon_from_file(os.path.join(base_path, 'images',
'sunflower.svg'))
```

This way we also end up with single copy of images, even if the system
have multiple Python versions installed at the same time and sunflower
is being installed for all of them.

The desktop file is also installed for me.

You might want to change get_version() a little bit, because currently
setup.py will not run without pygobject and chardet installed.

BTW, when using stdeb to create .deb package, it seems you can quite
simply specify other dependencies via --depends switch, see
https://github.com/astraw/stdeb, so it should automatically take care of
pythonish deps that are on pypi, and rest you can just add there.

-- Piotr.

**Comment by MeanEYE** [comment]
Thanks for the changes. I did test with a user of OpenBSD and it worked for
them. Not sure why it's not working for you. Probably something different in
configuration.

So .desktop file is installed? Does desktop environment find it and assigns icon
properly?

Also I did realize about get_version today. Not sure what I was thinking. I'll
have to fix that as soon as possible. I'll also take a look at stdeb.
-- 
Mladen Mijatov
Head of R&D, Way2CU

Key ID: 4096R/83EFD5A0 2013-08-18

**Comment by slashbeast** [comment]
What I did:
```
% virtualenv ~/tmp/venv
% . ~/tmp/venv/bin/activate
% pip install pygobject chardet
% pip install .
% rehash
% sunflower
```

which ended up with:
```
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/piotr/tmp/venv/lib/python3.8/site-packages/images/sunflower.svg”: No such file or directory (4)
```
Because the script does find it's way into sunflower module path under site-packages/ then use dirname, so it goes `../`, which is bare site-packages, however you install images into `$PREFIX/images` so it won't find it, and usually `$PREFIX` is `/usr`, but `/usr/images/` is not best place for it.

This is very generic way to reproduce it, so you can uninstall sunflower from your system, to not confuse Python, and try to install it as in develop branch via virtualenv. I am sure it will work the same way on Debian as it does on Gentoo.

**Comment by MeanEYE** [comment]
Ah, he installed it just with python3 setup.py install, which egg-dropped it to
a single location, images included. It didn't split them up. Would this change
you provided work with that case as well?

What does sys.prefix contain?

-- 
Mladen Mijatov
Head of R&D, Way2CU

Key ID: 4096R/83EFD5A0 2013-08-18

**Comment by slashbeast** [comment]
With system-wide Python, it's the /usr usually, with virtualenv, it's virtualenv root. see https://docs.python.org/3.8/library/sys.html#sys.prefix

Using bare `python3 setup.py install` will not yield you desired results, even without virtualenv you would want to use `pip` to install Python modules, as otherwise it will not fetch dependencies for you. See https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install

**Comment by MeanEYE** [comment]
Thanks. I'll test and check if it works as expected.
-- 
Mladen Mijatov
Head of R&D, Way2CU

Key ID: 4096R/83EFD5A0 2013-08-18

**Comment by MeanEYE** [comment]
It seems we will have to add additional check for `sys.prefix` since running Sunflower as Python module from the repository relies on check for `get_base_directory()`.

**Comment by slashbeast** [comment]
By running from repository you mean as in go to location where you have clone and running sunflower? I think you could write simple `sunflower` script inside root of your repository, that would `from sunflower import main`, and run `main()` like `main(prefix=os.path.dirname(__file__))`, while defaulting `def main(prefix=sys.prefix)`. I have not tested it, but it should cover all usecases, make it working when installed in virtualenv or systrem-wide, while allowing you to run it locally without installation.

**Comment by slashbeast** [comment]
My previous comment of course will require small overhaul of how you use `get_base_directory()` but It think it's for the best. Instead of making code be smart and during runtime determinate where it is and how to act, you will make it 'defined' in `main()`, at the very beginning, so all the later logic shouldn't be needed, making the code generic.

**Comment by MeanEYE** [comment]
Am not so sure about that kind of approach because it will complicate things with command line argument parsing and similar. Code needs to be aware of path anyway, since we have support for standalone zip modules, system installed images. So having another check is not that big of a deal as code only has it in two places (window icons and about window splash screen).

We'll see. I have to think about this one, because we use to have startup script and it caused nothing but problems for years. Took me a long time to get rid of it. Am hesitant about going back to such solution.

**Comment by MeanEYE** [comment]
Let me just confirm one thing. The only fix you had to do to start Sunflower was fix window icon loading? It didn't complain about styles and similar?

**Comment by slashbeast** [comment]
As long as you don't install it I see not a problem.

Is your flow to run it like: `PYTHON_PATH=`pwd` python -m sunflower`? If so, you could resolve sys.prefix to absolute path, and then check if `vars(sys.modules[__name__])['__file__']` starts with it

`if vars(sys.modules[__name__])['__file__'].startswith(os.path.abspath(sys.prefix))` unless someone uses /usr/src that is within sys.prefix.

But honestly, having a 'runner' that is not installed in module, or in any other way, just for quick testing, like:

```#!/usr/bin/env python3

from sunflower import main

main(prefix=os.path.dirname(os.path.abspath(__file__)))
```
Shouldn't introduce any issue, but would allow you to then pass default `prefix=` from main.py/__main__.py, you could even put a comment at the top to use it only for local development.

**Comment by slashbeast** [comment]
This is correct, but now when you ask, I think my $PWD was the source tree, let me retest.

**Comment by slashbeast** [comment]
Works regardless of current working directory with https://github.com/slashbeast/Sunflower/commit/2efb967a86743bcefe2e005c3a237697ee7e86f2 and this is how it looks https://i.imgur.com/vkm1Zgv.png

**Comment by MeanEYE** [comment]
Hm, then your solution might work. Can you open Help → About window and see if splash screen loads.

**Comment by MeanEYE** [comment]
There's also additional question of translations. Where do I put those?

**Comment by slashbeast** [comment]
It did not, but there are two problems there, one is that `about_window.py` sets `image_path` using `get_base_directory()` which gets the wrong directory, then it maps it to `path` object but then it also is not using this object, it does use check `sys.path` and hardcode(?) `with archive.open('images/splash.png') as raw_file:` so ignores the `path` object with absolute path, and fallback to `path = '/usr/share/pixmaps/sunflower/splash.png'`, since you have there `/usr`, you could also replace it with `sys.prefix` too. :)

I think by introducing `prefix` set to either current working directory, if running from in-source tree, that otherwise defaults to sys.prefix would be the best, and would also clean up a handful of if-o-logic blocks that determinate if to use local `images/` or to use the system wide `/usr`. by just using always the `prefix` object, that is to be proper and will not require checking in about window, again in icons.py etc.

**Comment by MeanEYE** [comment]
Yes, it seems this path handling needs some cleanup. I'll fix those tomorrow. Right now I have to deal with some other things. Regarding translations, any advice?

**Comment by slashbeast** [comment]
If you declare `base_directory` as either current working directory (in source tree) or `sys.prefix/sunflower` I would put it there and push to all functions it runs the base_directory to lookup for images, icons, translations. Midnight Commander does put them in `/usr/share/hints/mc.hint.*` and it seems to be okayish

**Comment by MeanEYE** [comment]
So there's no standardized way or location for them. Okay, thanks!

**Comment by MeanEYE** [comment]
Well my definition of tomorrow might a bit off, but I did push some changes today. Do you mind testing?

**Comment by cpcbegin** [comment]
I have the same problem with Debian 11 alpha and Ubuntu Mate 20.04 LTS.

**Comment by slashbeast** [comment]
You would need to be more clear what is the same problem. I suspect some code that was contributed by me might not work 100% the way it should. I still have on my todo to go back to it, meanwhile, can you be more specific?

**Comment by slashbeast** [comment]
The setup.py is present in repo, so thank you all, closing it.

**Comment by MeanEYE** [comment]
Is the issue solved?

**Comment by slashbeast** [comment]
Indeed it is, there's some work around sunflower and packaging but none the less, setup.py is functional.

**Comment by MeanEYE** [comment]
Glad to hear that. What kind of workarounds we need to do? Perhaps I could assist in that.

**Comment by slashbeast** [comment]
Currently the problem I see is that when installed via setup.py in Gentoo the about page have no functioning logo there, and this is the code I did modified in my MR so I am confident that I participated in it and I have idea how to fix it, I just need to sit to it and figure it out. :) WIll let you know either here or via MR if any MR is needed. This is on the old snapshot x11-misc/sunflower-0.4_p20200716-r1

**Comment by MeanEYE** [comment]
Please update the repo to latest version before endeavoring in solving this. It's just possible I fixed the issue since I made some changes in that are.a
