### ISSUE TITLE
Cannot open location containing spaces

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#388]
I have an optical disk with spaces in its label. It is displayed in Locations list, under Mounts section as "Ubuntu 20.04 LTS amd64". Selecting "Open" button results in error dialog:
````
Error changing working directory to:
/run/media/virtualbox/Ubuntu%2020.04%20LTS%20amd64
No such file or directory
Would you like to retry?
````

Below it hides another dialog (I presume it was opened first), with almost exactly the same text, only file URL is a bit different: `file:///run/media/virtualbox/Ubuntu%2020.04%20LTS%20amd64`

If I go to /run/media/virtualbox/ directory and open that drive - it works just fine.

**Comment by MeanEYE** [comment]
This whole mount management part of the program will get rewritten. It's a buggy mess and I don't like it like that.

**Comment by MeanEYE** [comment]
Now that new version is out. Is this issue fixed?

**Comment by joshas** [comment]
Yes, opening in same tab, new tab and even opposite panel works without issues.

**Comment by MeanEYE** [comment]
Good. Thank you! I had similar issues but they are gone now.
