### ISSUE TITLE
Help button in Preferences leads to empty page

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#392]
Pressing "Help" button in Preferences window results in web browser opening broken link.
Also, fixing link manually leads to empty wiki page on Gitlab: `https://gitlab.com/MeanEYE/Sunflower/wikis/home`.
What correct link should be used here? Fixing broken URL also is trivial, as it needs to be provided without https:// prefix.

**Comment by MeanEYE** [comment]
Only issue with that was the protocol prefix. Other than that URL you provided is correct, just WIFI is poor in content. If you take a look at the right side there are menu items which point out to coding style and other pages.
