### ISSUE TITLE
Please add me (mantas) to Lithuanian translation team

### ISSUE THREAD

**Issue by Baltix** [MeanEYE/Sunflower#394]
I can improve Lithuanian translation of Sunflower before 0.4 release :)

Please add me (mantas) to Lithuanian translation team at
https://www.transifex.com/way2cu/sunflower/

I'm translating free software since 1999, see https://wiki.ubuntu.com/MantasKriau%c4%8di%c5%abnas

**Comment by MeanEYE** [comment]
Sorry you had to open an issue like this. I try to bi vigilant with Transifex but their notification system leaves a lot to be desired. They did seem to have fixed it lately. Anyway... I added you!
