### ISSUE TITLE
Limit selection of toolbar icon sizes

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#395]
Currently user can select from big list of toolbar icon sizes, but three of them are the same size (16px). Titles are not very clear (what are "drag icons"?), it is hard to predict which one will be bigger or smaller without experimenting.
````
'Same as menu item' Gtk.IconSize.MENU - 16px
'Small toolbar icon' Gtk.IconSize.SMALL_TOOLBAR - 16px
'Large toolbar icon' Gtk.IconSize.LARGE_TOOLBAR - 24px
'Same as buttons' Gtk.IconSize.BUTTON - 16px
'Same as drag icons' Gtk.IconSize.DND - 32px
'Same as dialog' Gtk.IconSize.DIALOG - 48px
````

I'd like to suggest leaving only small and large toolbar icon sizes, because their names are quite clear. And 32px and 48px size icons are just too big for a toolbar. I've attached screenshots of those two.

![dialog](https://user-images.githubusercontent.com/79141/80748080-0b718680-8b2d-11ea-9575-e7b317363cb4.png "Gtk.IconSize.DIALOG")
![dnd](https://user-images.githubusercontent.com/79141/80748086-0ca2b380-8b2d-11ea-9f22-e3b9e7a0cf87.png "Gtk.IconSize.DND")

**Comment by MeanEYE** [comment]
Yeah, that's not very helpful. We should improve this.

**Comment by MeanEYE** [comment]
Thank you!
