### ISSUE TITLE
Installing on OpenBSD

### ISSUE THREAD

**Issue by j4n3b** [MeanEYE/Sunflower#404]
Hi;
I tried installing Sunflower on OpenBSD 6.7 amd64 edition:
I tried installing by issuing `python3 setup.py build` which didn't see any error and then `sudo python3 setup.py install` which I am getting:

```
Installing sunflower script to /usr/local/binInstalled /usr/local/lib/python3.7/site-packages/Sunflower-0.4.62-py3.7.eggProcessing dependencies for Sunflower==0.4.62Searching for giReading https://pypi.org/simple/gi/No local packages or working download links found for gierror: Could not find suitable distribution for Requirement.parse('gi')
```
here is the openbsd port search:
[openports](https://openports.se/devel/py-gobject3)

**Comment by MeanEYE** [comment]
Fixed.
