### ISSUE TITLE
Improve file operation error dialog

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#408]
File operation error dialog header has too many items.
![operation-error](https://user-images.githubusercontent.com/79141/82368637-6dcbf180-9a1e-11ea-81e8-cab65651bc2f.png)

**Comment by MeanEYE** [comment]
This shouldn't be displayed as this dialog anyway. Also, this error which just occurred was created by a PR some time go. `_ns` parameters were created to properly set timestamps. @multiSnow was the one who wrote it. Perhaps he's aware of this problem.

**Comment by joshas** [comment]
Probably not the best example for error, but I suppose this dialog might appear in other cases too?

**Comment by MeanEYE** [comment]
It shouldn't. Dialogs for confirmation need to be modal like this one:
![image](https://user-images.githubusercontent.com/1911594/82369274-09f1fa80-9a17-11ea-9e8f-619baa22feeb.png)
