### ISSUE TITLE
Overwrite dialog doesn't work

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#413]
When trying to overwrite file in opposite file panel, OverwriteDialog should show up. But now it fails with error message:
````
TypeError: could not convert value for property `transient_for' from Popover to GtkWindow
````

OverwriteDialog class is using Popover as parent:
https://github.com/MeanEYE/Sunflower/blob/3af53bd8fe029ad88afee8700a13240126d436ba/sunflower/gui/input_dialog.py#L1039-L1043

Should main window be used here instead?

**Comment by MeanEYE** [comment]
Thank you. This is a really bad one. Needs to be fixed as soon as possible.

**Comment by MeanEYE** [comment]
Fixed.
