### ISSUE TITLE
Calculate directory size.

### ISSUE THREAD

**Issue by edmundlaugasson** [MeanEYE/Sunflower#42]
When looking folders there is always question - does it contain something. It could reduce a lot of times when filemanager could show. how many files and folders are in it. Even properties shows only first level of items in folder...
Certainly - this should be configurable - on old computers it might be slow. But this feature could be smart - e.g. work in background, etc.

**Comment by joshas** [comment]
+1

**Comment by MeanEYE** [comment]
@joshas this is planned for v0.3 which should land any day now.
