### ISSUE TITLE
Contact function in Plugins Preferences fails without mail client set

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#425]
If user doesn't have default email client set, clicking Contact button in Plugins Preferences silently fails with error message in terminal. It would be nice if in this case we could show contact email in some form (either in plugin description or modal), that user could copy it and paste it to e.g. webmail client.

**Comment by MeanEYE** [comment]
Hm, this is indeed an issue.

**Comment by MeanEYE** [comment]
Just checked this and it's possible to right-click on person and option is available to copy link address. However I am fixing how `goto_web` is behaving.
