### ISSUE TITLE
Keyboard navigation improvements to Locations list

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#426]
Pressing "Enter" key in Locations list doesn't open selected location, seems as if focus is still in files list, although navigation with up/down arrows works as expected allowing to select location. Using keyboard for mounting/unmounting operations should be considered too.

**Comment by insolor** [comment]
Also, it would be useful, if double click on a location would open this location

**Comment by MeanEYE** [comment]
Yeah. The expected behavior was to select location and then chose what to do with it. Apparently this is not as obvious as I thought it would be. I'll change.

**Comment by MeanEYE** [comment]
This issue is now fixed however there's a different bug which is making pressing enter impossible. Main window for some reason only known to GTK developers takes over the handler.
