### ISSUE TITLE
Sunflower 0.4 does not work in Ubuntu and Debian

### ISSUE THREAD

**Issue by sania405** [MeanEYE/Sunflower#428]
I previously informed the author about this problem, but he ignores it and does not want to deal with the error in his own development. Version 0.4 does not work in Ubuntu.
I also downloaded the debian pack for Debian 10, and installed Sunflower 0.4 there too. The result is the same - the program does not turn on.
At the same time, I note that Sunflower 0.3 works in both systems. But in conditions when a minimal system is installed, in the window manager of Icewm, Sunflower 0.3 does not scale, and it does not drag on the desktop.
Developer! You either make a normal product, or do not create bug reports that you don’t respond to !!!
On a photo screen from Debian. A similar error in Ubuntu.
![Снимок экрана от 2020-06-20 13-10-20](https://user-images.githubusercontent.com/67229047/85225435-edf8c480-b3d9-11ea-9612-f1b7f4581759.png)

**Comment by MeanEYE** [comment]
The issue has been noted and fixed. It will be released with 0.5 soon. There is no need for toxic attitude, especially considering developers and contributors don't owe you anything. This is a project my contributors and I do in our own free time and give it away for free as a gesture of good will. Free time however is a luxury these days and demanding anything is just too much. Little patience goes a long way.

**Comment by MeanEYE** [comment]
As for other issues mentioned about not scaling and dragging, please report them separately.
