### ISSUE TITLE
Exception when opening preferences

### ISSUE THREAD

**Issue by icyrockcom** [MeanEYE/Sunflower#431]
When opening preferences, I get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sunflower/gui/preferences/item_list.py", line 599, in _handle_cursor_change
    self._columns_store.append((column, size, is_visible, font_size))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 997, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 988, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 900, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 914, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 210, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 249, in set_value
    raise TypeError("Expected string but got %s%s" %
TypeError: Expected string but got 10<class 'int'>
```

The dialog functions fine otherwise from what I see, just reporting it in case you are not running into this.

**Comment by MeanEYE** [comment]
Thanks for reporting this. Are you using custom columns?

**Comment by icyrockcom** [comment]
Well that's another issue - when I go to the Item List / Columns, it's empty.... I did just upgrade from prev version (0.3.61?) to the current one (0.4.62) and I was still using the old config. Moving `.config/sunflower` makes the above exception disappear. The old config had these columns in `plugins.json`:

```
    "FileList": {
        "columns": [
            "name",
            "extension",
            "size",
            "mode",
            "date"
        ],
        "font_size_date": 10,
        "font_size_extension": 10,
        "font_size_mode": 10,
        "font_size_name": 10,
        "font_size_size": 10,
        "size_date": 114,
        "size_extension": 106,
        "size_mode": 84,
        "size_name": 606,
        "size_size": 84
    }
```

Not sure if something there was to blame.

Anyway, looks like the workaround is to start with a fresh config :) Idk if it's worth investigating further given that, but I'll leave that up to you.

**Comment by MeanEYE** [comment]
Do you by any chance have the old config? I'd like to see where the issue occurs and prevent it from happening again.

**Comment by icyrockcom** [comment]
Yeah what I pasted above was from the old config. After removing the above `FileList` section from plugins.json, the exception disappears and Item List / Columns is now populated. I tested briefly and it looks like adding any of the `font_size_*` properties causes the exception to appear again. Removing all of `font_size_*` properties is enough to make it work without exceptions.

**Comment by MeanEYE** [comment]
Okay, thank you. This narrows it down quite a bit.

**Comment by icyrockcom** [comment]
Sure, let me know if you need more information to reproduce.

**Comment by MeanEYE** [comment]
This issue is now fixed. Please let me know if you run into it again!
