### ISSUE TITLE
Cropped context menu

### ISSUE THREAD

**Issue by reagentoo** [MeanEYE/Sunflower#434]
Hi,
Please fix the positioning of the context menu.
It goes outside the screen if you try to open it at the bottom of the screen.
https://i.imgur.com/EmZaTFt.png
My DE: Gnome3+wayland.

**Comment by MeanEYE** [comment]
I plan on rebuilding this menu with popovers. It's planned. Thank you for reporting.

**Comment by joshas** [comment]
Gtk.Menu.popup is deprecated. Documentation suggests using `Gtk.Menu.popup_at_widget()`, `Gtk.Menu.popup_at_pointer()` or `Gtk.Menu.popup_at_rect()` instead.
Replacing
https://github.com/MeanEYE/Sunflower/blob/6b4ad8db726764ce0153b5a45e3ca59d0eb68367/sunflower/plugin_base/item_list.py#L1232
with `self._popup_menu.popup_at_pointer()` fixes issue for mouse input.
As for case with accelerator key ("Menu"), used `popup_at_rect()`, but I'm still not sure about anchor points. I'll try to find cleaner solution and upload pull request.

After applying this fix, Sunflower no longer display following errors in terminal after opening context menu:
````
Gdk-Message: 22:52:09.104: Window 0x555a08541c60 is a temporary window without parent, application will not be able to position it on screen.
(Sunflower:22807): Gdk-CRITICAL **: 22:52:09.108: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
````

**Comment by MeanEYE** [comment]
Thank you for this tip. Indeed it does look like its deprecated.
