### ISSUE TITLE
Display title bar again

### ISSUE THREAD

**Issue by 3isenHeiM** [MeanEYE/Sunflower#436]
Hi,

There is a property to hide the title bar.
However, once done it I can't recover it, since the "parameters" button is in the title bar (which has been hidden).

Any hint on how to make it apprear again ?

Thanks

**Comment by MeanEYE** [comment]
Pressing `Ctrl+Alt+P` will open preferences and then in first tab you can check "show titlebar" again.

**Comment by 3isenHeiM** [comment]
This solved the problem, thanks !

**Comment by MeanEYE** [comment]
You are welcome! :)
