### ISSUE TITLE
Show link on folder icon

### ISSUE THREAD

**Issue by edmundlaugasson** [MeanEYE/Sunflower#44]
Somehow I would understand when folder is not actually folder but link - in Linux symlink and there is also hard link - it would be nice if there could be possible to make difference between them visually by using different symbols.

**Comment by nervgh** [comment]
Thanks for Sunflower! :sunflower:

I have same problem. I can not identify symlinks (files & folders) because they have not icons.

Sunflower 0.2 (59) on 64-bit Ubuntu 15.10
