### ISSUE TITLE
Sunflower is not using a system font in Mode and Date columns

### ISSUE THREAD

**Issue by AlexDaniel** [MeanEYE/Sunflower#440]
See this screenshot:
![image](https://user-images.githubusercontent.com/5507503/87717424-07aee100-c7b9-11ea-8226-028c6826f9ce.png)

The font is different in `Mode` and `Date` columns.
I think sunflower is forcing a different font even though the default one is already fixed-width.

**Comment by jtojnar** [comment]
It will use the monospace font chosen by fontconfig:

https://github.com/MeanEYE/Sunflower/blob/841252d0f05c029ef89f52e7547d3630ff20091d/sunflower/plugins/file_list/file_list.py#L341

Perhaps we should make it use GNOME’s monospace font like Terminal plug-in does:

https://github.com/MeanEYE/Sunflower/blob/841252d0f05c029ef89f52e7547d3630ff20091d/sunflower/plugin_base/terminal.py#L124

**Comment by MeanEYE** [comment]
You are right. We are using just generic monospace family name which doesn't seem to produce good results in your case. However, we can use `Gio.Settings` to derive proper font and just modify size that way.

The approach @jtojnar is talking about is the correct one. However font family that is specified in `cell_renderer` has to be string. So our approach would most likely be something like this:

```python
		settings = Gio.Settings.new('org.gnome.desktop.interface')
		font = settings.get_string('monospace-font-name')
```
