### ISSUE TITLE
Error clicking a button in locations without location selected

### ISSUE THREAD

**Issue by jtojnar** [MeanEYE/Sunflower#441]
After I open Sunflower, no location is selected and when I click any of the buttons, it triggers an error:

```
Traceback (most recent call last):
  File "/nix/store/vs2swfmhrfd1g964qgcc4arlzbs1waj4-sunflower-2020-07-03-unstable/lib/python3.8/site-packages/sunflower/widgets/location_menu.py", line 158, in __handle_open_tab_click
    options.set('path', selected_location.get_location())
AttributeError: 'NoneType' object has no attribute 'get_location'
```

**Comment by MeanEYE** [comment]
Can you be more specific on actions you took for this to happen? Which tabs were open, which locations. Did locations become unavailable due to unmount or something similar?

**Comment by jtojnar** [comment]
I had home directory open in both panes. This happens just after starting Sunflower – there is no location selected in the listbox in the locations popover until one clicks one of them.

**Comment by MeanEYE** [comment]
This was such a stupidly simply issue and I didn't get to it until now. So sorry for that. Basically I did some elementary checks but failed on logic. I have made necessary changes that address this issue. Thanks again for reporting.
