### ISSUE TITLE
Drag-and-Drop broken & unable to use Ctrl-C to quit

### ISSUE THREAD

**Issue by lucible** [MeanEYE/Sunflower#445]
System info: running Arch, i3 window manager, no desktop environment. Sunflower 0.3 worked great for me and I never had any complaints! After upgrading to 0.4 and being a little surprised at the UI change, I later discovered the following issues:

- drag-and-drop is broken. I attempted to drag a file from one panel to another to copy it, and nothing happened.
- minor issue: ctrl-q doesn't quit the program, which is frustrating. granted this is an issue with google chrome too (ugh) so I don't hold it against 0.4

Drag-and-drop is basically the whole reason I want to use a file manager so I downgraded to version 0.3. It's worth noting that my initial downgrade attempts were foiled by Sunflower 0.4 changing the `.config/sunflower/windows.json` file in such a way that Sunflower 0.3 couldn't read it. After deleting that particular config file, Sunflower 0.3 opened successfully and the rest of my config (open tabs etc) appears to be intact.

**Comment by MeanEYE** [comment]
Sorry about that. Version 0.4 is not all that ready yet. There were many
new bugs discovered. I released that version in hopes of making frequent
releases and getting back to old release schedule.

Using 0.3 is probably the smartest move if you are missing a critical
feature.

**Comment by MeanEYE** [comment]
Fixed. Please reopen if there are issues with my fix.
