### ISSUE TITLE
Missing image error when starting Sunflower

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#447]
Cloned latest version from repository and tried starting Sunflower with following command from terminal:
`python -m sunflower`
It fails complaining about missing image:
````Traceback (most recent call last):
  File "/home/user/projects/Sunflower/sunflower/__main__.py", line 163, in do_activate
    self.window = MainWindow(
  File "/home/user/projects/Sunflower/sunflower/gui/main_window.py", line 115, in __init__
    self.icon_manager.set_window_icon(self)
  File "/home/user/projects/Sunflower/sunflower/icons.py", line 136, in set_window_icon
    window.set_icon_from_file(os.path.join(base_path, 'images', 'sunflower.svg'))
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/user/projects/Sunflower/sunflower/images/sunflower.svg”: No such file or directory (4)

All images are actually located in main directory, not "sunflower" subdirectory.

**Comment by MeanEYE** [comment]
Thank you for reporting this one. I somehow missed it because I have my own package installed which is the first place where program looks for icon. I'll fix it.

**Comment by MeanEYE** [comment]
Basically one pull request managed to mess up whole situation with paths and assets. Even though this one is a simple fix, I will not be fixing it right away. I want to come up with a solution so this never happens again. It's a nightmare having to juggle wants of setup.py and all the other stuff.

**Comment by MeanEYE** [comment]
Anyway, I went on and fixed it. Please retest.

**Comment by joshas** [comment]
Now Sunflower starts without errors, thank you.

**Comment by MeanEYE** [comment]
Good to hear that. Handling shared paths is not as simple as it sounds. Each distribution has its own quirks.
