### ISSUE TITLE
Terminal font wonky

### ISSUE THREAD

**Issue by jtojnar** [MeanEYE/Sunflower#449]
Are you doing anything special to the terminal font? It looks misaligned for me compared to GNOME Terminal:

![Screenshot from 2020-10-03 17-15-02](https://user-images.githubusercontent.com/705123/94995090-1cbb3500-059c-11eb-948f-be2cf8f252f8.png)
![Screenshot from 2020-10-03 17-15-31](https://user-images.githubusercontent.com/705123/94995091-1dec6200-059c-11eb-86ea-6ce2dabdd1d1.png)

**Comment by jtojnar** [comment]
I am using the default font:

![Screenshot from 2020-10-03 17-22-39](https://user-images.githubusercontent.com/705123/94995207-17aab580-059d-11eb-9161-ddc0e195e4f5.png)


And actually even when I choose a different font manually nothing changes.

**Comment by jtojnar** [comment]
Actually, when I choose a font manually in Sunflower’s Terminal preferences and click save, it does not get applied because it raises an error:

```
Traceback (most recent call last):
  File "/nix/store/njsi0vygq275igv5ns2qsjp3hxavbc5r-sunflower-2020-07-16-unstable/lib/python3.8/site-packages/sunflower/gui/preferences_window.py", line 193, in _save_options
    self._parent.apply_settings()
  File "/nix/store/njsi0vygq275igv5ns2qsjp3hxavbc5r-sunflower-2020-07-16-unstable/lib/python3.8/site-packages/sunflower/gui/main_window.py", line 2174, in apply_settings
    page.apply_settings()
  File "/nix/store/njsi0vygq275igv5ns2qsjp3hxavbc5r-sunflower-2020-07-16-unstable/lib/python3.8/site-packages/sunflower/plugin_base/terminal.py", line 351, in apply_settings
    self._terminal.set_font_from_string(section.get('font'))
AttributeError: 'Terminal' object has no attribute 'set_font_from_string'
```

But after I restart it, it picks up the change:

![image](https://user-images.githubusercontent.com/705123/94995343-e67eb500-059d-11eb-9423-a0dc5e1a30f1.png)


Maybe the issue is that the system setting is missing Regular. But GNOME Terminal seems to handle that.

**Comment by MeanEYE** [comment]
These are two separate issues. 

That said, I am getting font from `org.gnome.desktop.interface.monospace-font-name`. So this issue shouldn't really happen with weird font. The other issue where it's calling unknown method I just fished and pushed fix for. Can you retest?

**Comment by jtojnar** [comment]
Yes, that fixes the secondary issue. Thanks.

Hmm, if I set the font manually, it still gets stored as `Monospace 11` in the config – exactly the same what `settings.get_string('monospace-font-name')` returns, so the `Regular` variant is only in the font chooser.

So I do not understand why `use_system_font` is wonky but setting the same font manually works.

**Comment by jtojnar** [comment]
Hmm, it is probably my mistake. If I manually change it to the same value as default it works:

![Screenshot from 2020-10-03 18-05-22](https://user-images.githubusercontent.com/705123/94996149-24caa300-05a3-11eb-8593-0cbb2c8db25f.png)

Most likely caused by an incompatible override I have.

**Comment by jtojnar** [comment]
Yeah, `gsettings-desktop-schemas` use `Source Code Pro 10` as the default monospace font but it is not installed on Ubuntu, which overrides the value to `Monospace 11`.

In Nixpkgs, we wrap programs to use upstream schemas in case they are not installed globally on the system so my Sunflower package on Ubuntu tried to use the default value from the upstream schemas and failed.

**Comment by MeanEYE** [comment]
Glad to hear you found the source of this issue. Thanks for reporting them!
