### ISSUE TITLE
Allow using GTK bookmarks

### ISSUE THREAD

**Issue by jtojnar** [MeanEYE/Sunflower#450]
Nautilus, Thunar and other file managers use GTK bookmarks (https://askubuntu.com/questions/192747/where-does-nautilus-store-bookmark-names). It would be nice if we could use them as well so that we can have the same bookmarks in the file manager and file chooser dialogue.

**Comment by MeanEYE** [comment]
We already support system bookmarks but you have to enable them first. Go to Settings -> Bookmarks -> Show system bookmarks.

**Comment by jtojnar** [comment]
Oh, my bad, sorry for the noise.

**Comment by MeanEYE** [comment]
No problem. Better to have duplicates than not have reports at all. :)
