### ISSUE TITLE
Unused _history_button_clicked function

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#462]
While updating menu popup functions in items list, I've found unused function, that is no longer called from anywhere:
https://github.com/MeanEYE/Sunflower/blob/d1bbfbcaa8dca490fac007ba649510eba6d57658/sunflower/plugin_base/item_list.py#L1259
Should it be removed, or are you planing to add history button to UI later?

**Comment by MeanEYE** [comment]
It can be removed. I want to unify all the locations (bookmarks, mounts, history) into single popover. This function you found was a button handler for dedicated history button.
