### ISSUE TITLE
New items and directories are added above "parent dir" row

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#464]
Commit 43d93a9beac236d5a6c43bfb1de0b62b697b0a8f introduced an issue: create file and create directory commands add new items above "parent dir" [..] item:
![Screenshot from 2020-10-06 23-21-43](https://user-images.githubusercontent.com/79141/95255983-de877500-082a-11eb-8d40-37c2f11f32b1.png)

New files created in other file managers also appear on top.

**Comment by MeanEYE** [comment]
Yes, noticed that myself as well. Thanks for reporting. Basically new approach with sorting is to have custom hidden column which is populated with data which GTK can use to sort items. Issue with this is that `generate_sort_data` is not called when adding new item so it ends up with empty data for sorting and GTK just puts it at top.

In addition to calling said method we should also modify it to support dedicated `iter_list` which can be provided to allow us to generate sort data only for few items and not whole list.

**Comment by joshas** [comment]
#489 fixed the issue.

**Comment by MeanEYE** [comment]
Thanks for closing the issue.
