### ISSUE TITLE
Remove Google+

### ISSUE THREAD

**Issue by frankenstein91** [MeanEYE/Sunflower#487]
I also miss Google+ as a platform, but it has been switched off for some years now. Nevertheless there are still many references to Google+ here and on the website. In my opinion, these references should be removed from the documentation to show that the development of this project has been resumed.

**Comment by MeanEYE** [comment]
Thanks for reporting this issue. I completely forgot about this. Removed.

**Comment by frankenstein91** [comment]
Many thanks for the fast implementation and good luck with the project.

**Comment by MeanEYE** [comment]
Thank you for reporting the issue and for good wishes! All the best!
