### ISSUE TITLE
Bookmarks aren't working at all

### ISSUE THREAD

**Issue by DigiAngel** [MeanEYE/Sunflower#497]
Topic..just installed the latest on Ubuntu 20....I Ctrl+F1 and F2 do nothing..I can't seem to get them working.  Am I missing something?

**Comment by MeanEYE** [comment]
Well, this is a story that ended on its own. :) To add to this in case you or someone else needs additional info...

Ctrl+F1 and F2 have issues on Gnome Shell under Wayland. It's a protocol specific issue for some reason unknown to me. There is no such issue when same Gnome Shell is started on top of X.org. You could remap the keys to something else and those would work, just function keys have issues.
