### ISSUE TITLE
Replace Copy Dialog with Copy Bar

### ISSUE THREAD

**Issue by omid** [MeanEYE/Sunflower#50]
I think instead of current copy/move/delete modal, better to have something like what we have in SpaceFM:
http://ehc.ac/p/spacefm/tickets/32/attachment/spacefm_manager.png

**Comment by joshas** [comment]
@MeanEYE With file operation modal already moved to popover, is there any reason to keep this issue open? Is there a plan to implement expandable file operation rows?

**Comment by MeanEYE** [comment]
No, this is basically it. I also plan on rendering a small progress bar in the main window header bar. Similar to what Nautilus does but all in all, this is implemented now.
