### ISSUE TITLE
Key bindings interfere with quick search

### ISSUE THREAD

**Issue by vfaronov** [MeanEYE/Sunflower#505]
In a default Sunflower configuration, I can’t do a quick search for `bar-baz.txt`, because as soon as I type the hyphen `-`, Sunflower interprets it as the key binding for “Deselect with pattern”.

I can work around this by rebinding the offending keys (which also include Space, +, Ctrl+Backspace), but it would be better if instead Sunflower preferentially interpreted keystrokes as editing the search query.

**Comment by MeanEYE** [comment]
Sorry for the late reply. Email got misplaced somehow. Anyway, quick search without any mods is already a default setting. However you are using a shortcut for deselecting by pattern. These shortcuts are actually copied from old file twin panel file managers like Norton Commander, Total Commander and others. I am afraid changing it would put too many people at discomfort. In this case customizing editor to your liking would be best.
