### ISSUE TITLE
Panel resized when navigating directories

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#51]
Pane size is narrow. When I go up a directory "information panel" above increases pane width to fit loading icon. After loading sometimes pane goes back to original width.
If pane width is big enough, this problem doesn't occur.

**Comment by joshas** [comment]
How about overlaying loading spinner over directory icon on the left? It would save space and indicate that actual directory is being read.

**Comment by MeanEYE** [comment]
Not a bad idea at all.
