### ISSUE TITLE
Plans for the future?

### ISSUE THREAD

**Issue by chiaravalle** [MeanEYE/Sunflower#519]
Hello. I'd like to know what's planned for the future, which features will be developed.

Specifically, I'd like to know if you'll support the following:
- FTP access
- Photo/PDF [pre]View
- Id3 tag management

Thanks a lot in advance for any, keep up the good work =)

Have a nice day, regards.

**Comment by MeanEYE** [comment]
Hi @chiaravalle. Thanks for inquiring. At the moment Sunflower is unfortunately stuck between my work and lack of free time. Transition to GTK3 was successful but some parts of the program still need to be rebuilt to look more modern and simpler. This is where FTP access comes into play. Sunflower is built on GIO, which supports FTP. So it already supports FTP. However mount manager which will allow you to create those connections is not upgraded yet. If you connect with Nautilus to FTP for example, Sunflower will see that connection and be able to use it.

PDF and photo preview is built as well, however it only shows small thumbnails. There's no whole pane view. This preview is called "Fast media preview" and can be located in "Menu -> View -> Faste media preview" option.

Id3 tag management is not present however. I do have couple of ideas what you mean by management, but can you explain in more details how you'd use this feature? Do you mean automatically assigning values to id3 tags based on file names?

**Comment by chiaravalle** [comment]
Wow, what nice to hear news!
As for the Id3 tags, it was just for curiosity, but more or less what you can do with Kid3 and the likes.
It's no problem to rely on Kid3 itself btw =)

**Comment by MeanEYE** [comment]
It's been a while since I released a new version and I should definitely find the time to wrap things up. At the moment I plan on supporting GTK4 since it fixes some of the issues with very little effort and it makes it look even more modern. Anyway, thanks for reaching out. If you have any more issues please let me know.
