### ISSUE TITLE
Selected item height is bigger

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#52]
All selected items in pane have bigger height than normal.

**Comment by MeanEYE** [comment]
Am having issues reproducing this on any fonts available on my system. Basically configuration in code is set up that way so that star is the same size as item name. Can you please change font and see if this issue happens still? Thanks!

**Comment by joshas** [comment]
It happens in Ubuntu 14.04.2 and Ubuntu 15.04 (with Unity). I booted up Live CD and installed Sunflower package for Ubuntu (sunflower-0.2.59-1.all.deb).
I think default font is "Ubuntu". Could it be that star symbol is not in Ubuntu font and fallback font is used?

**Comment by MeanEYE** [comment]
That's what I am suspecting. That Ubuntu font doesn't have that character and that causes increased height of items. You can also change this character manually to anything you want from preferences menu.
![2015-07-23-192441_405x374_scrot](https://cloud.githubusercontent.com/assets/1911594/8857209/7bd81e3c-3170-11e5-8712-f1f582ba1486.png)

**Comment by joshas** [comment]
I didn't know that it's an input field. I presumed that one can only select from predefined symbols.
Tried setting it to default star symbol - no issues with row height. But I prefer to leave it empty - color indication is enough for me.

**Comment by MeanEYE** [comment]
Okay. So it is a font issue and not something I can solve other than having different symbol. Am glad your issue is resolved. Am going to close this. Thanks for reporting.
