### ISSUE TITLE
Enhancement request %d and %F and %f command line parameters

### ISSUE THREAD

**Issue by VastOne** [MeanEYE/Sunflower#56]
To be able to pass information within Commands structure would greatly enhance the Sunflower

%d current directory
%F Selected Files or %f for first selected file

Example: 

su-to-root -X -c sunflower %d

would open a root instance of sunflower from within the directory you are in

su-to-root -X -c medit %f

would open a root medit session on the selected file

It would also be very helpful to have freedesktop.org standards such as $HOME or the tilda ~ (which represents /home) as config standards.  This way a default config can be setup for multiple users ... as in the case from an /etc/skel setup if used as the default file manager in a distro

**Comment by sevka** [comment]
I made few additional variables:
    %d, %D - (Directory) Name of the current directory of active list.
    %m, %M - (Multiselect) All selected items of active list
    %u, %U - (Universal/United) All selected items of active list. But if no selection, it returns names under cursor from left and right lists.
    
    Examples:
    /usr/bin/meld %U
    tar cvfz "%p.tgz" %m

You can find code in my fork of your wonderful project.

**Comment by MeanEYE** [comment]
Thanks.

**Comment by MeanEYE** [comment]
@sevka I've merged your code manually, but it still needs refinement. All those conditions are kind of chaotic. That said, whole method for parsing parameters is chaotic and needs improving anyway, hence the reason why I merged it.

In next few versions I'll add a mechanism for easily extending these parameters so we can reuse them in multiple places.

**Comment by MeanEYE** [comment]
See #162.
