### ISSUE TITLE
Recursive symlinks not supported

### ISSUE THREAD

**Issue by jschneider** [MeanEYE/Sunflower#62]
using Ubuntu:
try to copy /usr/bin/X11 (which is a link to "./") to another dir:
Calculation for needed space does never end.

**Comment by MeanEYE** [comment]
Thank you! I will fix this as soon as possible. Can you specify version? Thanks.

**Comment by jschneider** [comment]
Hmm. Downloaded the latest version from the home page today (deb). So I think it should be 0.2 (59).

**Comment by MeanEYE** [comment]
Okay thanks. Can you try downloading [development version](https://github.com/MeanEYE/Sunflower/archive/develop.zip) just to make sure this issue is not solved. I did some symlink checks in the mean time.

**Comment by jschneider** [comment]
Same problem with the development version.

**Comment by MeanEYE** [comment]
Okay, I will check. This shouldn't be happening.

**Comment by joshas** [comment]
@MeanEYE This issue can be closed, as it was fixed by https://github.com/ArseniyK/Sunflower/commit/36d43b6e6db91f968000a4cdabf690451d173e16 .

**Comment by MeanEYE** [comment]
Thanks for testing!
