### ISSUE TITLE
file:// prefix in mounted volumes paths

### ISSUE THREAD

**Issue by Taomach** [MeanEYE/Sunflower#63]
Recently, the paths of external volumes mounted by udisks2 started to look like `file:///run/media/$USER/$VOLUME`. Problem is, this path gets passed to the external applications associated with files and they do not always recognize it. For example, geeqie and inkscape fail to open files with such paths. Screenshot of the problem: http://i.imgur.com/ABHE1C0.png

**Comment by MeanEYE** [comment]
If application is being started by GIO then that's an issue with their desktop file. I suspect it's our fault in this case. Can you be more specific on how files are started? By pressing `enter` or going to _Open with_ menu? One of these should work.
