### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by FiSHYsolutions** [MeanEYE/Sunflower#67]
```
bash$ sunflower 
Attempt to unlock mutex that was not locked
Failed running with python2.7

bash$ sunflower -v
Sunflower 0.2f (59)

bash$ python -V
Python 2.7.6

bash$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty

bash$ ls -ld ~/.config/* | grep sunflower ; echo $?
1
```

**Comment by MeanEYE** [comment]
Thanks for reporting this issue. However this is a known issue with PyGTK which got messed up in one version and now half of the PyGTK applications is not working properly. Can you please try the [current development](https://github.com/MeanEYE/Sunflower/archive/develop.zip) version and see if that works.

**Comment by MeanEYE** [comment]
Duplicate from issue #33.

**Comment by FiSHYsolutions** [comment]
jep, this development release is working, but it has the same version information:
```
bash$ python Sunflower.py -v
Sunflower 0.2f (59)
```

and it spits out this warning after start:
```
bash$ python Sunflower.py 
/tmp/Sunflower-develop/application/plugins/file_list/file_list.py:318: GtkWarning: IA__gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
  int(gtk.Settings().get_property('gtk-font-name').split()[-1])
```

**Comment by MeanEYE** [comment]
Because I didn't release a new version yet. But I see how this can cause confusion. I should probably increase version as soon as version is released.

**Comment by joshas** [comment]
@MeanEYE I think this issue can be closed as obsolete, as new version uses Python 3.

**Comment by MeanEYE** [comment]
It is obsolete.
