### ISSUE TITLE
cant enter preferences

### ISSUE THREAD

**Issue by yagaev** [MeanEYE/Sunflower#68]
running on debian testing. when i run sunflower under user i cant enter preferences. nothing happens. when i start sunflower under root i can enter preferences.

**Comment by Taomach** [comment]
Seems like permissions problem. Who is the owner of the files in your `~/.config/sunflower`?

**Comment by yagaev** [comment]
I checked that - owner is the user. Also tryed to chmod 777 ...
I cant access any of subwindows of sunflower: prefs, bookmarks, etc.

**Comment by MeanEYE** [comment]
Can you start Sunflower from the terminal and let us know if there are some errors reported?

**Comment by yagaev** [comment]
when trying to enter to preferences

Traceback (most recent call last):
  File "/usr/share/sunflower/application/gui/preferences_window.py", line 131, in _show
    self._load_options()
  File "/usr/share/sunflower/application/gui/preferences_window.py", line 176, in _load_options
    page._load_options()
  File "/usr/share/sunflower/application/gui/preferences/plugins.py", line 224, in _load_options
    config.read(plugin_config)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/ni/.config/sunflower/user_plugins/extract/plugin.conf, line: 5
'<!DOCTYPE html>\n'

**Comment by MeanEYE** [comment]
Well, that's a user plugin issue.

**Comment by yagaev** [comment]
I deleted folder ~/.config/sunflower and it's solved issue. Thanks.

**Comment by MeanEYE** [comment]
Well, specifically it was extract plugin.
