### ISSUE TITLE
Port to GTK3 using PyGObject

### ISSUE THREAD

**Issue by guywithcrookedface** [MeanEYE/Sunflower#77]
I'm not sure if there is a way to do this, or if it's possible to do it in such a way where backward compatibility can still be achieved with GTK 2. Really nice work on this project by the way =D Posting this issue after someone commented that they would use this if it had GTK 3 widgets instead of GTK 2.

Original comment by Niko Lowry
* https://plus.google.com/+ChristopherDaleCanBeFoundHere/posts/PfYyC2KHg9u

Some information on porting to GTK+ 3
* https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject

**Comment by ArseniyK** [comment]
We already start porting to GTK3 https://github.com/MeanEYE/Sunflower/tree/gtk3

**Comment by guywithcrookedface** [comment]
Awesome, great news! Sorry I didn't see that earlier. I'll pass on the good news to Niko Lowry.

Thanks ArseniyK =D
