### ISSUE TITLE
Code does not follow PEP-8 guidelines

### ISSUE THREAD

**Issue by tiberiuichim** [MeanEYE/Sunflower#87]
See https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

Why spaces instead of tabs? It makes colaboration easier when a potential colaborator doesn't have to change his development environment to accomodate for this exception.

**Comment by MeanEYE** [comment]
Which code are you talking about in specific. Sunflower uses exclusively tabs. Besides using tabs doesn't break the convention.

**Comment by tiberiuichim** [comment]
Sorry, I meant "why use tabs instead of spaces"? And to quote the PEP8, "Spaces are the preferred indentation method. "

**Comment by MeanEYE** [comment]
Well, preferred and not mandatory. Also Sunflower was started with tabs and changing it right now is not that good of an idea. And using tabs is not breaking the convention, they just prefer spaces which I don't. Spaces are a lot less flexible. With tabs, you can set tab to be either 4 or 8 or 2. And code will still not change.

I seriously doubt use of tabs is deterring anyone from contributing if they really want to. Switching to spaces at this point would show no benefit in my opinion.
