### ISSUE TITLE
Move operation to network folder is not working

### ISSUE THREAD

**Issue by friek2k** [MeanEYE/Sunflower#90]
Hello,
it is not possible to move files to a mounted network folder (smb, ftp , nfs, ....). The operation dialog just hangs an does nothing. However the other direction (network folder to local) works fine. The error occurs with 0.2 (59) and todays trunk.

```
Traceback (most recent call last):
  File "/usr/share/sunflower/application/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/usr/share/sunflower/application/plugins/file_list/file_list.py", line 925, in _move_files
    operation.set_destination_queue(destination)
NameError: global name 'destination' is not defined
```

![unbenannt](https://cloud.githubusercontent.com/assets/11144478/6983088/240193a8-da1a-11e4-8a60-2eccf22af0f5.png)

**Comment by MeanEYE** [comment]
Okay, thanks for reporting this. There was a typo. I fixed and pushed this.
