### ISSUE TITLE
When adding bookmarks, note that underscore can be used as quick activation key.

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#91]
Like in TotalCommander, would be great to have the ability to assign a simple letter (aka accelerator) for a bookmarked folder. The bookmarks list then show the letters underlined, and the user can just press a key to move quickly to the desired folder.
 
A common historical and effective way is to put an  '&' just before the desired letter in the name of the bookmark.
Es. &Document.
 
OT/PS. really thanks for this projects!  it's about ten years I'm looking for the same feeling of total commander on linux...(even if I'm now almost accustomed with the MidnightCommander) this looks very promising.

**Comment by MeanEYE** [comment]
Bookmarks already have quick set of shortcuts `Alt + _Number_`, for example `Alt + 1` will go to first bookmark, etc. There's a special case shortcut `Alt + ~` (no `Shift`) which will take you to your home directory.

I can enable ampersand (`&`) to underscore.

**Comment by bfx** [comment]
Reading the wiki, I found that the commands can be "accelerated" using '_'. 
Tried now with the bookmarks, and worked too!!! 
So maybe using & it's redundant, and a short tip about the '_' behavior could be enough.

**Comment by MeanEYE** [comment]
Ah, you mean underscore. Okay, I completely forgot about that one. Yeah, it does work with that one. I'll add some additional information.
