### ISSUE TITLE
Keybinding conflicts not evaluated on changed preferences

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#93]
Example to reproduce
1. Change 'Bookmark current directory' from CRTL+D to CTRL+Shift+D
2. Change 'Show bookmarks for current list' from <whatever> to CTRL+D
3. Sunflower detect a keybindings conflicts
4. Answering YES disable the change made in 1

Looks like the detection works reading the saved preferences instead of the current edited

**Comment by MeanEYE** [comment]
Thanks!
