### ISSUE TITLE
 Move folders under same mount point don't use atomic move/rename

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#95]
Example for reproduce:
- move /home/me/test/subfolder to /home/me

With a subfolder containg a lot of files (or with a slow disk :p) it's noticeable that all folder tree is traversed and every files are moved.

If the source and destination folder are on the same filesystem (more specifically same mount point) the move could be done atomically with the rename (man 2 rename) system call.

**Comment by MeanEYE** [comment]
We do test for that and apply accordingly. I will investigate this issue. Thanks for reporting!

**Comment by bfx** [comment]
Thanks to you, hope you don't mind this "issues bombing", just writing down what I found while using the app for future improvements. 

Indeed, if you can tell me where to look in the code about the problems I'm raising up (of course, only if you already know without taking more time), maybe I could try to check myself (if I've time too)

**Comment by MeanEYE** [comment]
I don't mind. Testing is always good. :)

**Comment by bfx** [comment]
I agree!

**Comment by niknah** [comment]
I can't move things on gvfs samba share.  It says "Application is unable to handle specified data. Check if source items still exist."
Also, when I "move" things from the local file system to the same share, it doesn't work.  But if I "copy" and then delete it from the local file system, it works.
