### ISSUE TITLE
Feature request for full file path copy to clipboard from (right click on file) context menu

### ISSUE THREAD

**Issue by blissnd** [MeanEYE/Sunflower#98]
Mladen Mijatov <meaneye.rcf@gmail.com>
	
AttachmentsApr 12 (1 day ago)
		
to sunflower-fm
This feature already exists, but I agree that it should be in context menu, although that menu is getting bigger and much more confusing that I'd like to. I might end up putting it in the main menu. We'll see.

In mean time this feature and similar ones are as follow:
- Copy just path to clipboard: Shift + Ctrl + L
- Copy selected items full path to clipboard: Shift + Ctrl + C

If multiple items are selected, multiple paths will be copied.

Also, if you don't mind creating issue on https://github.com/MeanEYE/Sunflower/issues
so we can keep track of it and it doesn't get forgotten.

Thanks!

On 04/11/2015 08:54 PM, nath7153@gmail.com wrote:
> Sorry if this is already added and I haven't been able to find the
> option somewhere...There is already an excellent feature where one can
> do 'copy path to clipboard' for the current folder, but it would be
> brilliant if there was a feature to copy a filename only or an entire
> path that includes a filename displayed in the file list, like the
> Freecommander menu on Windows. Would be great if this was possible from
> the right-mouse-button context menu when right-clicking on a particular
> filename....
>

**Comment by MeanEYE** [comment]
Thanks!
